/*
 * generated by Xtext 2.9.1
 */
package org.xtuml.bp.ui.xtext.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.xtuml.bp.ui.xtext.myDsl.definition

@RunWith(XtextRunner)
@InjectWith(MASLInjectorProvider)
class MASLParsingTest{

	@Inject
	ParseHelper<definition> parseHelper;

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
