/**
 * generated by Xtext 2.9.2
 */
package org.xtuml.bp.xtext.masl.masl.types.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtuml.bp.xtext.masl.masl.types.SetTypeReference;
import org.xtuml.bp.xtext.masl.masl.types.TypesPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Set Type Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SetTypeReferenceImpl extends AbstractCollectionTypeReferenceImpl implements SetTypeReference {
	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SetTypeReferenceImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return TypesPackage.Literals.SET_TYPE_REFERENCE;
	}

} //SetTypeReferenceImpl
