= What's New in BridgePoint 7.0

== Release Highlights
* Eclipse 2020
* Java 11 
* Enhanced Integration with Ciera Java Model Compiler
* Epoch Time
* ASL Action Language Editing 

'''

=== Eclipse 2020 and Java 11

The Eclipse version underneath BridgePoint has been upgraded in this release to
Eclipse 2020-06.  The previous version of Eclipse was 4.7 (_Oxygen_) which
was released in 2017.  This brings BridgePoint up to a modern version of
Eclipse.  Recent updates to Eclipse have focused on performance.  The user will
find BridgePoint opens more quickly and feels more "snappy".  More information
about Eclipse 2020-06 may be found link:https://www.eclipse.org/eclipseide/2020-06/[at this link].

Simultaneously, BridgePoint is upgraded to support and use Java 11.  BridgePoint now
uses a Java 11 JRE/JDK from the system; it is no longer inside the BridgePoint installation. 
These changes provide user experience and security improvements.  However,
the user is now responsible to install and maintain Java.  Find specifics to configuring
the Java Virtual Machine (JVM) in the https://github.com/xtuml/bridgepoint/blob/master/doc-bridgepoint/process/FAQ.md[FAQ].

=== Enhanced Integration with Ciera Java Model Compiler

Significant investment into _Ciera_ is included in this release of BridgePoint
and in the Ciera model compiler proper.  BridgePoint + Ciera represent a
solid model-based Java development combination.

Ciera is hosted on GitHub, https://github.com/xtuml/ciera[github.com/xtuml/ciera].

=== Epoch Time

The Time (TIM) External Entity (EE) has been enhanced to include support
for several new bridge operations which can manipulate time.  The base of
the epoch can now be modified.  Time can be advanced as well as set arbitrarily.
Binary comparison operations are now permitted on time values.  Read the original
specification for project https://onefact.net/wp-content/uploads/2020/05/Panda11939SRS.pdf[Panda].

Model Verifier, the interpretive runtime model simulator/debugger is updated
to support the new epoch time bridge operations.  The _Ciera_ Java model
compiler is extended to support the enhanced time operations.

In the BridgePoint model editor, the updated Time (TIM) EE is included in the
package context menu which allows users to import the built-in external entities.

=== Preliminary ASL Support

ASL is now an editable dialect of action language in BridgePoint.  ASL can
be selected as a dialect for any action semantics buffer in an xtUML model.

Model conversion, import/export and additional support for ASL are coming
soon in an upcoming release.

