= Handle CLI Prebuild Parse Errors

xtUML Project Implementation Note

== 1 Abstract

Support non-zero exit status for BridgePoint CLI Prebuild when parse errors exist.

== 2 Introduction and Background

The BridgePoint CLI currently will return a successful exit status as long as there are no exceptions. Customers would like to see a non-zero exit when any parse error is found.

== 3 Requirements

=== 3.1 Return non-zero status when parse errors are found
=== 3.2 Parse All unit tests pass

== 4 Work Required

=== 4.1 Return non-zero status when parse errors are found

The execution path between the CLI prebuild launch and the parser runs is convoluted. Handling the control flow through return values for this one particular case introduces unnecessary complexity. Oon top of this, the parser is not designed to return a single value. Rather parse exceptions are thrown and reported.

Rather than adjust the control flow using a single return value, a new mechanism is added that collects parse errors that are created during a parse run. Error collectors are not required, but if they exist they are notified during error reporting.

For the CLI prebuild case an error collector is added to the CoreExport instance used. The exporter then adds this collector to the list which shall be notified during reporting.

When completing the prebuild the code shall now return the count of parse errors collected, if there are none it returns a succesfull zero as it did before.

If the prebuild command specifies that a parse shall not occur, an additional check ignore parse error collection.

== 5 Implementation Comments

== 6 Unit Test

_- Run Parse All tests  +
_R All tests pass

== 7 User Documentation

== 8 Code Changes

- fork/repository: FMAY-Software/bridgepoint
- branch: feature/onefact-12310

---

src/org.xtuml.bp.als.oal/src/org/xtuml/bp/als/oal/TextParser.java
src/org.xtuml.bp.cli/src/org/xtuml/bp/cli/Build.java
src/org.xtuml.bp.cli/src/org/xtuml/bp/cli/BuildExecutor.java
src/org.xtuml.bp.cli/src/org/xtuml/bp/cli/BuildWorkbenchAdvisor.java
src/org.xtuml.bp.core/META-INF/MANIFEST.MF
src/org.xtuml.bp.core/src/org/xtuml/bp/core/activity/errors/ActivityError.java
src/org.xtuml.bp.core/src/org/xtuml/bp/core/activity/errors/ErrorCollector.java
src/org.xtuml.bp.core/src/org/xtuml/bp/core/common/IAllActivityModifier.java
src/org.xtuml.bp.io.core/src/org/xtuml/bp/io/core/CoreExport.java
src/org.xtuml.bp.mc.java/src/org/xtuml/bp/mc/java/McJavaBuilder.java
src/org.xtuml.bp.mc/src/org/xtuml/bp/mc/AbstractExportBuilder.java
src/org.xtuml.bp.core/src/org/xtuml/bp/core/activity/errors/ActivityError.java
src/org.xtuml.bp.core/src/org/xtuml/bp/core/activity/errors/ErrorCollector.java

---

== 9 Document References

. [[dr-1]] https://support.onefact.net/issues/12310[12310 - headline]

---

This work is licensed under the Creative Commons CC0 License

---
