/*
 * generated by Xtext 2.9.2
 */
package org.xtuml.bp.xtext.masl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMASLScopeProvider extends DelegatingScopeProvider {
}
