= Unintended Marking Deletions Issue Design Note
:numbered:
:sectnums:
:sectnumlevels: 5

xtUML Project Analysis Note

== Abstract

Unintended deletions are being made to the application.mark files when model
elements are renamed or moved.

== Introduction and Background

See <<dr-1>>.

== Requirements

See <<dr-1>>.

== Analysis

See <<dr-1>> for explanation of what is occuring.

Exploration using the debugger has shown that insufficient information is
available at MarkTransactionListener.start function, so all handling needs to 
occur at the end of transaction. 

The IModelChangeListener was also evaluated as another option, but this occurs 
before the transaction handling. There would be no recourse for cancellation or
undoing the transaction.

The point in the end of transaction handling where the problem occurs is at the
MarkingData.recalculatePathKeys function call; right before this call, the
marking data is collected, and the marking data contents are stale with respect
to the change.

The issue with an element change only occurs when the path is modified; this
occurs for DELTA_ATTRIBUTE_CHANGE transactions only. Any algorithm changes
should be predicated upon only this transaction.

recalculatePathKeys modifies the collected marking data. A fix has to occur
before or during the call to recalculatePathKeys.

== Design

=== Keyletter change persist

The keyletter mark data can be updated before the call to recalculatePathKeys,
so a new MarkingData method will be created to handle it. There is no need to
run recalculate path keys for a keyletter transaction.

=== Class rename fix


== Design Comments

== User Documentation

== Unit Test

== Document References
. [[dr-1]]
https://github.com/xtuml/bridgepoint/blob/master/doc-bridgepoint/notes/11787-mark-update-issues/11787-mark-update-issues-ant.adoc[11787 Mark Update Issues Analysis Note]
---

This work is licensed under the Creative Commons CC0 License

---

