= Unintended Marking Deletions Issue Design Note
:numbered:
:sectnums:
:sectnumlevels: 5

xtUML Project Analysis Note

== Abstract

Unintended deletions are being made to the application.mark files when model
elements are renamed or moved.

== Introduction and Background

See <<dr-1>>.

== Requirements

See <<dr-1>>.

== Analysis

See <<dr-1>> for explanation of what is occuring.

Exploration using the debugger has shown that insufficient information is
available at MarkTransactionListener.start function, so all handling needs to 
occur at the end of transaction. 

The IModelChangeListener was also evaluated as another option, but this occurs 
before the transaction handling. There would be no recourse for cancellation or
undoing the transaction.

The point in the end of transaction handling where the problem occurs is at the
MarkingData.recalculatePathKeys function call; right before this call, the
marking data is collected, and the marking data contents are stale with respect
to the change.

The issue with an element change only occurs when the path is modified; this
occurs for DELTA_ATTRIBUTE_CHANGE transactions only. Any algorithm changes
should be predicated upon only this transaction.

recalculatePathKeys modifies the collected marking data. A fix has to occur
before or during the call to recalculatePathKeys.

Path issues can be due to nrme attribute setting. For a valid set of named 
marks, the nrme attribute shouldn't be null, but the race conditions discussed 
in <<dr-1>> are in play.

The race conditions also come into play when the nrme attribute is valid. In
this case, the new value for a named element is in place, but the old value is
being used to recalculate the path.

== Design

=== Value change persist

The mark value attribute data can be updated before the call to recalculate the
new path, so a new MarkingData method will be created to handle it.

Some value data updates can also be due to named path changes, so this new
method and the update path method must both be run for the transaction.

=== Path name change fix

A mechanism for updaating the path name will be added to the path calculation in
such a manner that the old name will be checked, and then if it fails, the new
name will be checked. The result handling will then proceed as written.

=== Asterix support

Asterix detection will be added to the path calculation and marks with an
asterix will not be modified. As asterix support in values isn't required, the
value update method will not have any special handling for asterix.

== Design Comments

These fixes will not solve all issues with marks getting deleted that might be
caused by <<dr-2>>.

== User Documentation

== Unit Test

== Document References
. [[dr-1]] https://github.com/xtuml/bridgepoint/blob/master/doc-bridgepoint/notes/11787-mark-update-issues/11787-mark-update-issues-ant.adoc[11787 Mark Update Issues Analysis Note]
. [[dr-2]] https://support.onefact.net/issues/11472[11472 - Deadlock during load (parent)]
---

This work is licensed under the Creative Commons CC0 License

---

