= Unintended Marking Deletions Issue Implementation Note

xtUML Project Implementation Note

== 1 Abstract

== 2 Introduction and Background

== 3 Requirements

== 4 Work Required

=== 4.1 Value change persist

Added new method to MarkingData.java, MarkingData::updateValueData. The
method searches the collected marking data and updates marks that have the 
same value as the old value to be updated to the new value.

The marks also have to have the same NonRootModelElement(NRME), otherwise two 
different marks with the same value data could get updated. As there is a 
possible race condition between the initialization of the marking data and the 
initialization of the model, a null check is performed on the current mark's 
nrme. If null, then a call is made to getNRMEForMark to attempt to get a valid 
NRME. 

The method returns true, if the marking data was updated.

The method is called from MarkTransactionListener::transactionEnded, after the
marking data is collected and before the call to recalculatePathKeys. The method
call is predicated upon the transaction being a DELTA_ATTRIBUTE_CHANGE.

=== 4.2 Path name change fix

Changed MarkingData.java method, recalculatePathKeys, to include a retry
mechanism, if the call to getPathKey fails to produce a valid path key. The
retry mechanism requires data about the transaction, so the deltaToHandle value
is passed as a new parameter.

The retry mechanism first modifies the path with the new value. This might
require multiple retries, as a path can contain multiples of the same string.
e.g., A package named, ALU, contains a component named, ALU, which contains a 
package named, ALU, and results in a path of ALU::ALU::ALU, so a change of the
component name to ALG means the new path needs to be named ALU::ALG::ALU. Each
rename candidate is passed to getPathKey until a valid key is found or all
substitutions have been exhausted. i.e., possible substitutions are: 
ALG::ALU::ALU, ALU::ALG::ALU, or ALU::ALU::ALG.

After the retry mechanism is complete, the same marking data update method as
used in the previous recalculatePathKeys is performed.

The method is called from MarkTransactionListener::transactionEnded, after the
marking data is collected and the call to updateValueData. Both the calls to
updateValueData and recalculatePathKeys are performed, and if either indicates
a marking data update was performed, then the marking data is persisted.

=== 4.3 Asterix support

Support wwas added to MarkingData.java methods, updateValueData, updateFeature 
and recalculatePathKeys. 

In updateFeature, a check was added before the value of Mark.nrme is written, 
and if an asterix is in the path, Mark.nrme is set to null (unknowable).

In recalculatePathKeys, a check was added at the start of the path processing.
If the element's path is an asterix, then the mark data is retained unchanged,
otherwise the path processing proceeds.

In updateValueData a check for asterix is placed in case of a null NRME. As the
asterix indicates that the value applies to multiple elements.

=== 4.4 Exclusion of non-mark processing.

MarkingData::recalculatePathKeys was modified to add a check if the current
element's path contains the old value of a DELTA_ATTRIBUTE_CHANGE transaction. 
If the current element's path doesn't contain the old value, there's no reason 
to continue checking it. The mark data is retained unchanged.

== 5 Implementation Comments

The race condition between the model loading and marking data initialization
makes this issue impossible to fix completely.

== 6 Unit Test

No unit tests were added or chagned for this issue. Added unit tests could check
for value changes or asterix handling.

== 7 User Documentation


== 8 Code Changes

- fork/repository: lwriemen/bridgepoint
- branch:  11787-masl-disappearing-marks
----
 Put the file list here
----

== 9 Document References
. [[dr-1]]
https://github.com/xtuml/bridgepoint/blob/master/doc-bridgepoint/notes/11787-mark-update-issues/11787-mark-update-issues-ant.adoc[11787 Mark Update Issues Analysis Note]
. [[dr-2]]
https://github.com/xtuml/bridgepoint/blob/master/doc-bridgepoint/notes/11787-mark-update-issues/11787-mark-update-issues-dnt.adoc[11787 Mark Update Issues Design Note]

---

This work is licensed under the Creative Commons CC0 License

---
