= Timer misfire when using non-deterministic non-simulated settings

xtUML Project Implementation Note

== 1 Abstract

This note describes a changed to prevent timer misfiring when a launch target is configured to run non-deterministically and non-simulated.  In this case the debug session will use a shared timer thread across invocations.

== 2 Introduction and Background

The <<dr-1,headline issue>> talks about cases where timers stop firing in verifier at certain times.  Then models being verified in these cases will not run.

== 3 Requirements

3.1 Verifier timers should fire consistently when using shared timer thread.

== 4 Work Required

4.1 Do not disable shared timer thread

Investigation into this work shows that a single thread is used across multiple verifier invocations.  This thread is held as a static variable in the TIM implementation.  The logic during BPDebugTarget terminate checks a list of targets and stops the timers if there are no longer targets being run.  The call to stop the timers will toggle a static flag of running and will expect the thread to shutdown.

In the specific issues specified in the <<dr-1, 12015>>, ARCH::shutdown is used to terminate the verifier invocation.  A larger problem exists here in that the call to BPDebugTarget is never called in this case.  This leaves the shared thread running, with a boolean value of running set to false.  While this is set to false the thread will not process any timer events.  Upon another launch a new thread will not be initialized and therefore will not be set to running true.

For this work the thread will be left as running true.  This will have the effect of a verifier clock thread always waiting in sleep after the first use.  This thread will then be reused as necessary.  This thread being left over has no implications on the performance of the tool.

Another issue shall be raised to better handle ARCH::shutdown.

== 5 Implementation Comments

== 6 Unit Test

- Follow test iin <<dr-1>>, last comment 
- The timers fire with subsequent executions

== 7 User Documentation

== 8 Code Changes

- fork/repository:  travislondon/bridgepoint
- branch:  12015_timers

----
org.xtuml.bp.core/src/lib/TIM.java
----

== 9 Document References
. [[dr-1]] https://support.onefact.net/issues/12015[12015 - Timers stop ticking in Verifier.]

---

This work is licensed under the Creative Commons CC0 License

---
