= Curly bracket in ASL causing Java crash during regex compile

xtUML Project Implementation Note

== 1 Abstract

See <<dr-2>>.

== 2 Introduction and Background

See <<dr-2>>.

== 3 Requirements

See <<dr-2>>.

== 4 Work Required

The creator of <<dr-1>> noted that this issue wasn't present under Java 8, so it
seems that the actual issue may be in Java 11, not BridgePoint. Work should be
done to check for an existing Java 11 issue.

In the mean time, the points of failure in the code can be modified to escape 
any opening curly brackets.

== 5 Implementation Comments

<<dr-2>> only noted one point of failure, but after fixing that point, another
was discovered in MarkingData::recalculatePathKeys. This point was also fixed as
well as a second use of a matches call with a regex pattern in thesame
aforementioned method.

If an issue in Java 11 is discovered, then this issue should be revisited if
BridgePoint is updated with a fixed Java version to see if the fixes for this
issue can be removed.

== 6 Unit Test

== 7 User Documentation

== 8 Code Changes

- fork/repository:  lwriemen/bridgepoint
- branch:  12203_regex_compile_curly

----
org.xtuml.bp.ui.marking/src/org/xtuml/bp/ui/marking/MarkingData.java
----

== 9 Document References

. [[dr-1]] https://support.onefact.net/issues/12203[12203 - "Transaction Ended"
  Java Crash on Save]
. [[dr-2]] link:12203_regex_compile_curly_ant.adoc[Curly bracket in ASL causing Java crash during regex compile Analysis Note]

---

This work is licensed under the Creative Commons CC0 License

---
