= Curly bracket in ASL causing Java crash during regex compile

xtUML Project Analysis Note

== 1 Abstract

Issue <<dr-1>> shows an error in execution of an edit on an domain function
using ASL. This analysis determined the error to be attributable to the
invocation of a regex compile.


== 2 Introduction and Background

The issue writer provided a sample model with notations on where the error
occured and how it manifested. The issue writer also noted that the issue had
been tested on an older BridgePoint using Java 8, and the issue didn't manifest
with this older version of BridgePoint and older version of Java (Java 11 is now
required on newer BridgePoint versions).

The writer of the issue had noted that the ASL line:

---

\{the_bottles} = find-all Bottle

---

was involved in the error, and this was significant.

== 3 Requirements

=== 3.1 Curly brackets

Curly brackets are valid ASL, so BridgePoint should not produce a run time 
error when curly brackets exist in action language.

== 4 Analysis

Running a debug build of BridgePoint showed the point of error to be in 
MarkingData::updateValueData() at the point of call of 

---

markValue.matches(".*\\b" + oldAttributeValue + "\\b.*")

---

Stepping into the *matches* call showed that when the regex was run through a 
*compile* call the error was produced.

As a line involving curly brackets was noted, investigating removing the curly 
brackets resulted in no error. Further investigation showed: footnote:[If the
previous edit of the file contained the opening curly brace, then the current
edit would result in an error. Multiple edits were needed for analysis.]

. The opening curly bracket always caused the error.
. The first time the opening curly bracket was added, there was no error.
. Escaping the curly bracket caused no error to be produced.


== 5 Work Required

Change the handling of the regex expression to allow curly braces.

== 6 Acceptance Test

Rerun the test sequence attached to <<dr-1>>.

== 7 Document References

In this section, list all the documents that the reader may need to refer to.
Give the full path to reference a file.

. [[dr-1]] https://support.onefact.net/issues/12203[12203 - "Transaction Ended"
  Java Crash on Save]

---

This work is licensed under the Creative Commons CC0 License

---
