/**
 * generated by Xtext 2.9.1
 */
package org.xtuml.bp.ui.xtext.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>domain Function Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtuml.bp.ui.xtext.myDsl.domainFunctionDefinition#getS <em>S</em>}</li>
 *   <li>{@link org.xtuml.bp.ui.xtext.myDsl.domainFunctionDefinition#getR <em>R</em>}</li>
 * </ul>
 *
 * @see org.xtuml.bp.ui.xtext.myDsl.MyDslPackage#getdomainFunctionDefinition()
 * @model
 * @generated
 */
public interface domainFunctionDefinition extends definition
{
  /**
   * Returns the value of the '<em><b>S</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>S</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>S</em>' containment reference.
   * @see #setS(serviceVisibility)
   * @see org.xtuml.bp.ui.xtext.myDsl.MyDslPackage#getdomainFunctionDefinition_S()
   * @model containment="true"
   * @generated
   */
  serviceVisibility getS();

  /**
   * Sets the value of the '{@link org.xtuml.bp.ui.xtext.myDsl.domainFunctionDefinition#getS <em>S</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>S</em>' containment reference.
   * @see #getS()
   * @generated
   */
  void setS(serviceVisibility value);

  /**
   * Returns the value of the '<em><b>R</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>R</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>R</em>' containment reference.
   * @see #setR(returnType)
   * @see org.xtuml.bp.ui.xtext.myDsl.MyDslPackage#getdomainFunctionDefinition_R()
   * @model containment="true"
   * @generated
   */
  returnType getR();

  /**
   * Sets the value of the '{@link org.xtuml.bp.ui.xtext.myDsl.domainFunctionDefinition#getR <em>R</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>R</em>' containment reference.
   * @see #getR()
   * @generated
   */
  void setR(returnType value);

} // domainFunctionDefinition
