/**
 * generated by Xtext 2.9.1
 */
package org.xtuml.bp.ui.xtext.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>find Name</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtuml.bp.ui.xtext.myDsl.findName#getI1 <em>I1</em>}</li>
 *   <li>{@link org.xtuml.bp.ui.xtext.myDsl.findName#getI2 <em>I2</em>}</li>
 *   <li>{@link org.xtuml.bp.ui.xtext.myDsl.findName#getE <em>E</em>}</li>
 * </ul>
 *
 * @see org.xtuml.bp.ui.xtext.myDsl.MyDslPackage#getfindName()
 * @model
 * @generated
 */
public interface findName extends EObject
{
  /**
   * Returns the value of the '<em><b>I1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>I1</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>I1</em>' attribute.
   * @see #setI1(String)
   * @see org.xtuml.bp.ui.xtext.myDsl.MyDslPackage#getfindName_I1()
   * @model
   * @generated
   */
  String getI1();

  /**
   * Sets the value of the '{@link org.xtuml.bp.ui.xtext.myDsl.findName#getI1 <em>I1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>I1</em>' attribute.
   * @see #getI1()
   * @generated
   */
  void setI1(String value);

  /**
   * Returns the value of the '<em><b>I2</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>I2</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>I2</em>' attribute list.
   * @see org.xtuml.bp.ui.xtext.myDsl.MyDslPackage#getfindName_I2()
   * @model unique="false"
   * @generated
   */
  EList<String> getI2();

  /**
   * Returns the value of the '<em><b>E</b></em>' containment reference list.
   * The list contents are of type {@link org.xtuml.bp.ui.xtext.myDsl.expression}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>E</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>E</em>' containment reference list.
   * @see org.xtuml.bp.ui.xtext.myDsl.MyDslPackage#getfindName_E()
   * @model containment="true"
   * @generated
   */
  EList<expression> getE();

} // findName
