/**
 * generated by Xtext 2.9.1
 */
package org.xtuml.bp.ui.xtext.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>loop Variable Spec</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtuml.bp.ui.xtext.myDsl.loopVariableSpec#getS <em>S</em>}</li>
 * </ul>
 *
 * @see org.xtuml.bp.ui.xtext.myDsl.MyDslPackage#getloopVariableSpec()
 * @model
 * @generated
 */
public interface loopVariableSpec extends forStatement
{
  /**
   * Returns the value of the '<em><b>S</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>S</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>S</em>' containment reference.
   * @see #setS(statementList)
   * @see org.xtuml.bp.ui.xtext.myDsl.MyDslPackage#getloopVariableSpec_S()
   * @model containment="true"
   * @generated
   */
  statementList getS();

  /**
   * Sets the value of the '{@link org.xtuml.bp.ui.xtext.myDsl.loopVariableSpec#getS <em>S</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>S</em>' containment reference.
   * @see #getS()
   * @generated
   */
  void setS(statementList value);

} // loopVariableSpec
