/**
 * generated by Xtext 2.9.1
 */
package org.xtuml.bp.ui.xtext.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>parameter Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtuml.bp.ui.xtext.myDsl.MyDslPackage#getparameterDefinition()
 * @model
 * @generated
 */
public interface parameterDefinition extends EObject
{
} // parameterDefinition
