/**
 * generated by Xtext 2.9.1
 */
package org.xtuml.bp.ui.xtext.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtuml.bp.ui.xtext.myDsl.statement#getC <em>C</em>}</li>
 *   <li>{@link org.xtuml.bp.ui.xtext.myDsl.statement#getE <em>E</em>}</li>
 *   <li>{@link org.xtuml.bp.ui.xtext.myDsl.statement#getS <em>S</em>}</li>
 *   <li>{@link org.xtuml.bp.ui.xtext.myDsl.statement#getN <em>N</em>}</li>
 *   <li>{@link org.xtuml.bp.ui.xtext.myDsl.statement#getR <em>R</em>}</li>
 *   <li>{@link org.xtuml.bp.ui.xtext.myDsl.statement#getD <em>D</em>}</li>
 *   <li>{@link org.xtuml.bp.ui.xtext.myDsl.statement#getL <em>L</em>}</li>
 *   <li>{@link org.xtuml.bp.ui.xtext.myDsl.statement#getG <em>G</em>}</li>
 *   <li>{@link org.xtuml.bp.ui.xtext.myDsl.statement#getI <em>I</em>}</li>
 *   <li>{@link org.xtuml.bp.ui.xtext.myDsl.statement#getF <em>F</em>}</li>
 *   <li>{@link org.xtuml.bp.ui.xtext.myDsl.statement#getW <em>W</em>}</li>
 * </ul>
 *
 * @see org.xtuml.bp.ui.xtext.myDsl.MyDslPackage#getstatement()
 * @model
 * @generated
 */
public interface statement extends EObject
{
  /**
   * Returns the value of the '<em><b>C</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>C</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>C</em>' containment reference.
   * @see #setC(EObject)
   * @see org.xtuml.bp.ui.xtext.myDsl.MyDslPackage#getstatement_C()
   * @model containment="true"
   * @generated
   */
  EObject getC();

  /**
   * Sets the value of the '{@link org.xtuml.bp.ui.xtext.myDsl.statement#getC <em>C</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>C</em>' containment reference.
   * @see #getC()
   * @generated
   */
  void setC(EObject value);

  /**
   * Returns the value of the '<em><b>E</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>E</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>E</em>' containment reference.
   * @see #setE(EObject)
   * @see org.xtuml.bp.ui.xtext.myDsl.MyDslPackage#getstatement_E()
   * @model containment="true"
   * @generated
   */
  EObject getE();

  /**
   * Sets the value of the '{@link org.xtuml.bp.ui.xtext.myDsl.statement#getE <em>E</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>E</em>' containment reference.
   * @see #getE()
   * @generated
   */
  void setE(EObject value);

  /**
   * Returns the value of the '<em><b>S</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>S</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>S</em>' containment reference.
   * @see #setS(EObject)
   * @see org.xtuml.bp.ui.xtext.myDsl.MyDslPackage#getstatement_S()
   * @model containment="true"
   * @generated
   */
  EObject getS();

  /**
   * Sets the value of the '{@link org.xtuml.bp.ui.xtext.myDsl.statement#getS <em>S</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>S</em>' containment reference.
   * @see #getS()
   * @generated
   */
  void setS(EObject value);

  /**
   * Returns the value of the '<em><b>N</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>N</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>N</em>' attribute.
   * @see #setN(String)
   * @see org.xtuml.bp.ui.xtext.myDsl.MyDslPackage#getstatement_N()
   * @model
   * @generated
   */
  String getN();

  /**
   * Sets the value of the '{@link org.xtuml.bp.ui.xtext.myDsl.statement#getN <em>N</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>N</em>' attribute.
   * @see #getN()
   * @generated
   */
  void setN(String value);

  /**
   * Returns the value of the '<em><b>R</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>R</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>R</em>' containment reference.
   * @see #setR(returnStatement)
   * @see org.xtuml.bp.ui.xtext.myDsl.MyDslPackage#getstatement_R()
   * @model containment="true"
   * @generated
   */
  returnStatement getR();

  /**
   * Sets the value of the '{@link org.xtuml.bp.ui.xtext.myDsl.statement#getR <em>R</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>R</em>' containment reference.
   * @see #getR()
   * @generated
   */
  void setR(returnStatement value);

  /**
   * Returns the value of the '<em><b>D</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>D</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>D</em>' containment reference.
   * @see #setD(EObject)
   * @see org.xtuml.bp.ui.xtext.myDsl.MyDslPackage#getstatement_D()
   * @model containment="true"
   * @generated
   */
  EObject getD();

  /**
   * Sets the value of the '{@link org.xtuml.bp.ui.xtext.myDsl.statement#getD <em>D</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>D</em>' containment reference.
   * @see #getD()
   * @generated
   */
  void setD(EObject value);

  /**
   * Returns the value of the '<em><b>L</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>L</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>L</em>' containment reference.
   * @see #setL(linkStatement)
   * @see org.xtuml.bp.ui.xtext.myDsl.MyDslPackage#getstatement_L()
   * @model containment="true"
   * @generated
   */
  linkStatement getL();

  /**
   * Sets the value of the '{@link org.xtuml.bp.ui.xtext.myDsl.statement#getL <em>L</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>L</em>' containment reference.
   * @see #getL()
   * @generated
   */
  void setL(linkStatement value);

  /**
   * Returns the value of the '<em><b>G</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>G</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>G</em>' containment reference.
   * @see #setG(generateStatement)
   * @see org.xtuml.bp.ui.xtext.myDsl.MyDslPackage#getstatement_G()
   * @model containment="true"
   * @generated
   */
  generateStatement getG();

  /**
   * Sets the value of the '{@link org.xtuml.bp.ui.xtext.myDsl.statement#getG <em>G</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>G</em>' containment reference.
   * @see #getG()
   * @generated
   */
  void setG(generateStatement value);

  /**
   * Returns the value of the '<em><b>I</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>I</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>I</em>' containment reference.
   * @see #setI(ifStatement)
   * @see org.xtuml.bp.ui.xtext.myDsl.MyDslPackage#getstatement_I()
   * @model containment="true"
   * @generated
   */
  ifStatement getI();

  /**
   * Sets the value of the '{@link org.xtuml.bp.ui.xtext.myDsl.statement#getI <em>I</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>I</em>' containment reference.
   * @see #getI()
   * @generated
   */
  void setI(ifStatement value);

  /**
   * Returns the value of the '<em><b>F</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>F</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>F</em>' containment reference.
   * @see #setF(forStatement)
   * @see org.xtuml.bp.ui.xtext.myDsl.MyDslPackage#getstatement_F()
   * @model containment="true"
   * @generated
   */
  forStatement getF();

  /**
   * Sets the value of the '{@link org.xtuml.bp.ui.xtext.myDsl.statement#getF <em>F</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>F</em>' containment reference.
   * @see #getF()
   * @generated
   */
  void setF(forStatement value);

  /**
   * Returns the value of the '<em><b>W</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>W</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>W</em>' containment reference.
   * @see #setW(whileStatement)
   * @see org.xtuml.bp.ui.xtext.myDsl.MyDslPackage#getstatement_W()
   * @model containment="true"
   * @generated
   */
  whileStatement getW();

  /**
   * Sets the value of the '{@link org.xtuml.bp.ui.xtext.myDsl.statement#getW <em>W</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>W</em>' containment reference.
   * @see #getW()
   * @generated
   */
  void setW(whileStatement value);

} // statement
