/**
 * generated by Xtext 2.9.2
 */
package org.xtuml.bp.xtext.masl.masl.structure;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Relationship Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtuml.bp.xtext.masl.masl.structure.StructurePackage#getRelationshipDefinition()
 * @model
 * @generated
 */
public interface RelationshipDefinition extends AbstractNamed, Pragmatized {
} // RelationshipDefinition
