/**
 * generated by Xtext 2.9.2
 */
package org.xtuml.bp.xtext.masl.masl.structure;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtuml.bp.xtext.masl.masl.structure.StructurePackage
 * @generated
 */
public interface StructureFactory extends EFactory {
	/**
	 * The singleton instance of the factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	StructureFactory eINSTANCE = org.xtuml.bp.xtext.masl.masl.structure.impl.StructureFactoryImpl.init();

	/**
	 * Returns a new object of class '<em>Masl Model</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Masl Model</em>'.
	 * @generated
	 */
	MaslModel createMaslModel();

	/**
	 * Returns a new object of class '<em>Abstract Top Level Element</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Abstract Top Level Element</em>'.
	 * @generated
	 */
	AbstractTopLevelElement createAbstractTopLevelElement();

	/**
	 * Returns a new object of class '<em>Abstract Feature</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Abstract Feature</em>'.
	 * @generated
	 */
	AbstractFeature createAbstractFeature();

	/**
	 * Returns a new object of class '<em>Pragmatized</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Pragmatized</em>'.
	 * @generated
	 */
	Pragmatized createPragmatized();

	/**
	 * Returns a new object of class '<em>Pragma</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Pragma</em>'.
	 * @generated
	 */
	Pragma createPragma();

	/**
	 * Returns a new object of class '<em>Pragma Value</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Pragma Value</em>'.
	 * @generated
	 */
	PragmaValue createPragmaValue();

	/**
	 * Returns a new object of class '<em>Parameter</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Parameter</em>'.
	 * @generated
	 */
	Parameter createParameter();

	/**
	 * Returns a new object of class '<em>Project Definition</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Project Definition</em>'.
	 * @generated
	 */
	ProjectDefinition createProjectDefinition();

	/**
	 * Returns a new object of class '<em>Domain Definition</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Domain Definition</em>'.
	 * @generated
	 */
	DomainDefinition createDomainDefinition();

	/**
	 * Returns a new object of class '<em>Domain Service Declaration</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Domain Service Declaration</em>'.
	 * @generated
	 */
	DomainServiceDeclaration createDomainServiceDeclaration();

	/**
	 * Returns a new object of class '<em>Domain Service Definition</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Domain Service Definition</em>'.
	 * @generated
	 */
	DomainServiceDefinition createDomainServiceDefinition();

	/**
	 * Returns a new object of class '<em>Exception Declaration</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Exception Declaration</em>'.
	 * @generated
	 */
	ExceptionDeclaration createExceptionDeclaration();

	/**
	 * Returns a new object of class '<em>Terminator Definition</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Terminator Definition</em>'.
	 * @generated
	 */
	TerminatorDefinition createTerminatorDefinition();

	/**
	 * Returns a new object of class '<em>Terminator Service Declaration</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Terminator Service Declaration</em>'.
	 * @generated
	 */
	TerminatorServiceDeclaration createTerminatorServiceDeclaration();

	/**
	 * Returns a new object of class '<em>Terminator Service Definition</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Terminator Service Definition</em>'.
	 * @generated
	 */
	TerminatorServiceDefinition createTerminatorServiceDefinition();

	/**
	 * Returns a new object of class '<em>Builtin Library Definition</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Builtin Library Definition</em>'.
	 * @generated
	 */
	BuiltinLibraryDefinition createBuiltinLibraryDefinition();

	/**
	 * Returns a new object of class '<em>Characteristic</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Characteristic</em>'.
	 * @generated
	 */
	Characteristic createCharacteristic();

	/**
	 * Returns a new object of class '<em>Type Parameter</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Type Parameter</em>'.
	 * @generated
	 */
	TypeParameter createTypeParameter();

	/**
	 * Returns a new object of class '<em>Range Type Reference</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Range Type Reference</em>'.
	 * @generated
	 */
	RangeTypeReference createRangeTypeReference();

	/**
	 * Returns a new object of class '<em>Object Declaration</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Object Declaration</em>'.
	 * @generated
	 */
	ObjectDeclaration createObjectDeclaration();

	/**
	 * Returns a new object of class '<em>Object Definition</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Object Definition</em>'.
	 * @generated
	 */
	ObjectDefinition createObjectDefinition();

	/**
	 * Returns a new object of class '<em>Attribute Definition</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Attribute Definition</em>'.
	 * @generated
	 */
	AttributeDefinition createAttributeDefinition();

	/**
	 * Returns a new object of class '<em>Identifier Definition</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Identifier Definition</em>'.
	 * @generated
	 */
	IdentifierDefinition createIdentifierDefinition();

	/**
	 * Returns a new object of class '<em>Object Service Declaration</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Object Service Declaration</em>'.
	 * @generated
	 */
	ObjectServiceDeclaration createObjectServiceDeclaration();

	/**
	 * Returns a new object of class '<em>Object Service Definition</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Object Service Definition</em>'.
	 * @generated
	 */
	ObjectServiceDefinition createObjectServiceDefinition();

	/**
	 * Returns a new object of class '<em>Relationship Definition</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Relationship Definition</em>'.
	 * @generated
	 */
	RelationshipDefinition createRelationshipDefinition();

	/**
	 * Returns a new object of class '<em>Regular Relationship Definition</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Regular Relationship Definition</em>'.
	 * @generated
	 */
	RegularRelationshipDefinition createRegularRelationshipDefinition();

	/**
	 * Returns a new object of class '<em>Assoc Relationship Definition</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Assoc Relationship Definition</em>'.
	 * @generated
	 */
	AssocRelationshipDefinition createAssocRelationshipDefinition();

	/**
	 * Returns a new object of class '<em>Relationship End</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Relationship End</em>'.
	 * @generated
	 */
	RelationshipEnd createRelationshipEnd();

	/**
	 * Returns a new object of class '<em>Subtype Relationship Definition</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Subtype Relationship Definition</em>'.
	 * @generated
	 */
	SubtypeRelationshipDefinition createSubtypeRelationshipDefinition();

	/**
	 * Returns a new object of class '<em>Relationship Navigation</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Relationship Navigation</em>'.
	 * @generated
	 */
	RelationshipNavigation createRelationshipNavigation();

	/**
	 * Returns a new object of class '<em>Object Or Role</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Object Or Role</em>'.
	 * @generated
	 */
	ObjectOrRole createObjectOrRole();

	/**
	 * Returns a new object of class '<em>Event Definition</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Event Definition</em>'.
	 * @generated
	 */
	EventDefinition createEventDefinition();

	/**
	 * Returns a new object of class '<em>State Declaration</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>State Declaration</em>'.
	 * @generated
	 */
	StateDeclaration createStateDeclaration();

	/**
	 * Returns a new object of class '<em>State Definition</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>State Definition</em>'.
	 * @generated
	 */
	StateDefinition createStateDefinition();

	/**
	 * Returns a new object of class '<em>Transition Table</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Transition Table</em>'.
	 * @generated
	 */
	TransitionTable createTransitionTable();

	/**
	 * Returns a new object of class '<em>Transition Row</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Transition Row</em>'.
	 * @generated
	 */
	TransitionRow createTransitionRow();

	/**
	 * Returns a new object of class '<em>Transition Option</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Transition Option</em>'.
	 * @generated
	 */
	TransitionOption createTransitionOption();

	/**
	 * Returns the package supported by this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the package supported by this factory.
	 * @generated
	 */
	StructurePackage getStructurePackage();

} //StructureFactory
