= 12523 Verifier Association Phrases

xtUML Project Implementation Note

== 1 Abstract

Verifier was observed to incorrectly display relationship phrases in 
Session Explorer when showing participant instances in reflexive associations.  


== 2 Introduction and Background

Details of the incorrect behavior are captured here: <<dr-3>>.

== 3 Requirements

 Reflexive association phrases shall be displayed correctly.
 

== 4 Work Required

Study the Verifier code implementing association linkages to 
understand the erroneous behavior and correct it.

== 5 Implementation Comments

On examination, the code implementing association 'relate' in Verifier was 
found to be poorly designed and overly complex. In particular, the 
implementation was observed to make little use of downward navigation 
from the Association data structures, opting instead to attempt multiple 
upward navigations from the statement variables.


=== 5.1 The heart of the issue.

The challenge is to correctly identify the 'direction' of an association being 
related, with respect to the ordering of the participant instances in the 
'relate' statement and the choice of association phrase used in the statement.

In the case of reflexive associations, both participants are of the same class; 
it is necessary to discriminate between 'from' and 'to' participants by 
comparing the relationship phrase used in the 'relate' statement to the mandatory phrases 
held by the association data structure. When the association is formalized, this 
is readily done, as the Association data structure distinguishes between the 
'formalizer' and the 'participant'.

In the case of unformalized reflexive associations, however, it is not possible to 
distinguish between the two 'participant' (R_PART instances) representing the 
'source' and 'destination' variables - as in "relate source to destination".
 If, in this context, relate statements with mixed choice of phrase are used, the 
result may be less than useful.


=== 5.2 The implementation changes.

The code was greatly simplified by making use of Association data structure information 
where simple associations are formalized. It proved convenient to swap the order of the 
source and destination variables when a 'backward' relate was identified - i.e. when the 
'participant' variable came first in the statement. This simplified the logic when 
validating multiplicity and also when establishing the linkages which implement the association.

While not strictly necessary as part of this work, the code for associative relationships 
shared the poor design noted above; it was deemed appropriate to overhaul this while having a 
clear and current understanding of what was needed.

The function used to supply the relationship phrase for display was slightly modified to 
match the code changes to the relationship implementation.

== 6 Unit Test

The simple test model supplied in the original issue was used to validate the code change,
and updated with several tests to validate that the changes did not introduce errors in 
relationships other than reflexives.

== 7 User Documentation

None: this work merely corrected erroneous behavior.

== 8 Code Changes

- https://github.com/amullarney/bridgepoint
- 12532_verifier_associations

----
In org.xtuml.bp.core
Relate And Unrelate::Relate::execute
Relate And Unrelate::Relate Using::execute
Instance::Link Participatio9n::Label

----

== 9 Document References


. [[dr-1]] https:https://support.onefact.net/issues/12523 - headline]

---

This work is licensed under the Creative Commons CC0 License

