= Keep marks in sync with changing model elements 

xtUML Project Design Note

== 1 Abstract

"A user had a lot of pain because he renamed a signal and lost marks associated
with it, because the mark is tied to the name and signature.  BP just silently
got rid of the associated marks. So his stuff just stopped working and he didn’t
know why."

This comes from a Nov 17, 2018 discussion between One Fact and users about
high-priority items.

== 2 Introduction and Background

This work aims to make working with the marking editor easier by keeping
model elements in sync with their marks when the model elements change (e.g. 
name change, add parameter, etc).

Additional background may be found in the analysis note <<dr-2>>.

== 3 Requirements

3.1 Element marks shall be updated when an edit causes the path key for the element to change.

== 4 Analysis

See <<dr-2>>.

== 5 Design

- Store pointer to NRME in marking data in memory
- New transaction listener
- Update `MarkingEditorDialog` to handle the case where the marks are already loaded in memory before the dialog is opened.

-----
Having a bit of trouble getting the marking listener going at startup because the new listener is in the 
ui.marking plugin, which is lazy loaded.  This may not be the best solution, but for now I have added a
call to CorePlugin that loads the bundle and a class by name.  This forces the lazy load to occur.  

// Load a bundle without creating an osgi dependency.  This pattern is already used in many places
// in BP core.
final String packageName = "org.xtuml.bp.ui.marking"; //$NON-NLS-1$
    Bundle bundle = Platform.getBundle(packageName);
    try {
        bundle.loadClass( packageName + "." + "MarkTransactionListener");//$NON-NLS-1$ //$NON-NLS-2$
    } catch (ClassNotFoundException e) {
        e.printStackTrace();
    }
-----

// Load marking data for each project after the project is loaded
  // Add code at line 515 at end of PersistenceManager::initialize()

// Support overloaded terminator services by storing them with their signature
  
// If the application.mark or feature.mark is not found, it would be better to just log a message and not 
// throw an exception that generates a full stack trace...

== 6 Design Comments

None.

// What happens if the marking data is changed in the files on disk outside of BridgePoint?  Right now the file is re-read on every invocation
// of the marking dialog.  That will no longer happen.

// fix bug in TerminatorService::getSignature() that always added "void" to the return type porting of the signature string

== 7 User Documentation

None. 

== 8 Unit Test

// Deleting a package that contains a marked class
// Delete marked top-level package
// Delete marked sub-level package
// Delete a marked function 
// Test overloaded functions (Rename/delete/move)
// Rename a package that contains multiple marks
// Rename of an interface param does not persist the in-memory mods to disk
// Change return type on interface signal
// add param to interface signal
// remove param from interface signal

== 9 Document References

. [[dr-1]] https://support.onefact.net/issues/11634[11634 - Keep marks in sync with changing model elements]
. [[dr-2]] link:../11555_marking/11555_marking_ant.adoc[Marking enhancement analysis note]

---

This work is licensed under the Creative Commons CC0 License

---
