= Keep marks in sync with changing model elements 

xtUML Project Implementation Note

== 1 Abstract

"A user had a lot of pain because he renamed a signal and lost marks associated
with it, because the mark is tied to the name and signature.  BP just silently
got rid of the associated marks. So his stuff just stopped working and he didn’t
know why."

This comes from a Nov 17, 2018 discussion between One Fact and users about
high-priority items.

== 2 Introduction and Background

This work aims to make working with the marking editor easier by keeping
model elements in sync with their marks when the model elements change (e.g. 
name change, add parameter, etc).

Additional background may be found in the analysis note <<dr-2>>.

== 3 Requirements

3.1 Element marks shall be updated when an edit causes the path key for the element to change.

== 4 Analysis

See <<dr-2>>.

== 5 Design

5.1  Data Handling Changes

Because the primary functionality of this change deals with the in-
memory marking data, we deemed it best to add the bulk of the new functionality
in the `org.xtuml.bp.ui.marking` plugin rather than core.  

However, we needed the ability to get the new listener up and running right 
as BridgePoint is starting up.  It needs the ability to start watching model
changes right away before the user even considers the underlying impacts of
their model changes on marking.

The challenge is that the `ui.marking` plugin is lazy loaded and won't activate
until one of its contained pieces of functionality is needed.  Another challenge
is that it is unacceptable to create a dependency where `bp.core` has a 
dependency specified on an external plugin.  We want `bp.core` to be at the root
of the dependency tree.

5.1.1  To deal with these requirements, we follow a pattern already used in 
the BridgePoint code where `bp.core` needs this "soft" dependency to `ui.canvas`.
The approach is to use a raw function invocation out of a bundle loaded by
name only and not specify a dependency in the `bp.core` plugin metadata. This
causes the marking plugin to be loaded and activated.  This "soft" dependency
is created in `PersistenceManager.java` after model data is loaded.

5.2 `MarkTransactionListener`

A core piece of the new functionality for this work is a class named `MarkTransactionListener`. As
the name states it listens to transactions happening in the tool.  If the transaction
could have affected application model elements then it calls out to the 
`MarkingData` class to recalculate path keys as necessary.

5.3 `MarkingData`

This class is primarily a data structure that stores information about each
mark.  It is modified by this work to keep a pointer to the `NonRootModelElement`
that a mark is associated with.  Because model transactions affect these
`NRME` instances we can now positively keep track of what marking data must
change in response to transactions. 

This work also added a number of helper functions in this class to 
calculate path keys, perform manipulations on the collection of marking
data, etc. 
 
5.4 `MarkingDataManager`

This class has been added to keep the marking data for all projects in the
workspace in memory while BridgePoint is running. Previously the marking
data was only in memory on a per-project basis as the marking dialog was
active.  
 
5.5 `MarkingEditorDialog`

The dialog is updated to leverage the markings stored and persisted by 
the `MarkingDataManager` rather than loading and persisting the information
by itself.


== 6 Design Comments

6.1  Fixed bug in `TerminatorService::getSignature()` that always added "void" to 
the return type portion of the signature string:
```
  ...
  // Get return type
  select one returntype related by self->S_DT[R1656];
  signature = signature + returntype.Name + " ";
-  signature = signature + "void ";
end if;
```

== 7 User Documentation

None. 

== 8 Unit Test

See <<dr-3>>.

== 9 Code Changes

- fork/repository: __keithbrown/bridgepoint__ 
- branch: __11634_signal_mark_sync__ 

----
doc-bridgepoint/notes/11634_signal_mark_sync/11634_mark_sync_dnt.adoc
src/org.xtuml.bp.core/models/org.xtuml.bp.core/ooaofooa/Deployment/Terminator Service/Terminator Service.xtuml
src/org.xtuml.bp.core/src/org/xtuml/bp/core/common/PersistenceManager.java
src/org.xtuml.bp.ui.marking/src/org/xtuml/bp/ui/marking/Activator.java
src/org.xtuml.bp.ui.marking/src/org/xtuml/bp/ui/marking/MarkTransactionListener.java
src/org.xtuml.bp.ui.marking/src/org/xtuml/bp/ui/marking/MarkingData.java
src/org.xtuml.bp.ui.marking/src/org/xtuml/bp/ui/marking/MarkingDataManager.java
src/org.xtuml.bp.ui.marking/src/org/xtuml/bp/ui/marking/MarkingEditorDialog.java
----

== 10 Document References

. [[dr-1]] https://support.onefact.net/issues/11634[11634 - Keep marks in sync with changing model elements]
. [[dr-2]] link:../11555_marking/11555_marking_ant.adoc[Marking enhancement analysis note]
. [[dr-3]] https://support.onefact.net/issues/11683[11683 - Marking data listener tests]

---

This work is licensed under the Creative Commons CC0 License

---
