= Symmetric Reflexive Associations

xtUML Project Analysis Note

== 1 Abstract

The BridgePoint editor requires that role phrases be used on reflexive associations.
These should differ (not enforced, at present) so that navigation in either 
direction can be readily specified by choice of phrase in any statement that 
initiates or traverses the association.

So the simple reflexive association between, say, aquaintances, for example, must 
be burdened with the artificial directional phrases 'knows" and 'is known by'- a 
poor representation of the true relationship - enforcing a non-symmetrical view of 
what clearly should be seen as symmetrical.

For a symmetric reflexive association only one set of phrase, multiplicity and 
conditionality should describe the association. This will require modification to 
association editing, association implementation and selection logic.

As this feature will affect Model Compilers and Verifier, it is anticipated that,
initially, Verifier will be enhanced in parallel with the Editor to provide an 
execution environment for acceptance testing.

== 2 Introduction and Background

This work explores what must be done to support navigation when only one role 
phrase is available; what must be modified in 'select' logic; and how the 
association editor dialog must be enhanced.

Consider the association that declares that territories may be adjacent 
to one another, as in: +
  relate CA to AZ across R1.'is adjacent to'; +
 then both: +
  select any territory related by CA->Territory[R1.'is adjacent to']; and +
  select any territory related by AZ->Territory[R1.'is adjacent to']; +
 must yield correct results. +
 Note that the association can be navigated in either direction regardless of 
the order in which the association was instantiated. That is, +
  relate AZ to CA across R1.'is adjacent to'; +
 is equivalent to the first 'relate' shown above. 

== 3 Requirements

=== 3.1 Association Editor dialog

Support creation of symmetric reflexive associations, with or without an associative class.

==== 3.1.1

Present a checkbox to select for symmetry only when the association is reflexive.

==== 3.1.2

If symmetry is selected, suppress the second, now redundant, set of fields: labels, 
conditionality, multiplicity and phrase specification.

=== 3.2 Relate and Unrelate semantics

Support for relate and unrelate in either direction, without concern for the ordering of the 
instance variables in the statement.

==== 3.2.1

When two instances are related symetrically, either instance can be selected from 
the other using the same role phrase.
==== 3.2.2

When two instances are related symetrically, they may be unrelated from one another 
in either direction using the same role phrase.

=== 3.3 Navigation

==== 3.3.1

Relationship navigation must allow for 'fan-out' across symmetric reflexive 
associations with multiplicity, recognizing that links may have been established in either 
direction.

==== 3.3.2

Navigation from an associative class instance must allow for either or both 
related instances to be retrieved using the single available role phrase.

=== 3.4 Content assist

Suppress the presentation of a symmetric relationship number with an empty role phrase

==== 3.4.1

For relate and unrelate, only one instance of a symmetric association number, 
decorated with a role phrase, shall be offered.

==== 3.4.2

When creating a relationship chain including a symmetric association only one 
instance of a symmetric association number, decorated with a role phrase, shall be offered.

=== 3.5 Verifier display

Any display of an instance of a symmetric association shall include the role phrase.

==== 3.5.1

Session Explorer shall display a role phrase for symmetric associations.

==== 3.5.2

Variables display shall show a role phrase for symmetric associations.

==== 3.5.3

Variables display shall show all instances related across a symmetric reflexive 
in a single list.

== 4 Analysis

The meta-model association data structure (Package: Association) does not 
offer explicit support for the concept of reflexive associations, still 
less symmetric. The reflexive nature must be deduced by recognizing that both  
participants are of the same class. 

Associations are defined on the canvas by drawing a connector between classes. 
The direction in which the connector is drawn defines a referring/referred-to 
'directionality' for the association. Non-symmetric reflexive associations 
require differing role phrases to distinguish directionality in relating, 
unrelating, selecting or navigation. Symmetric reflexive associations can only 
specify a single role phrase, hence directionality cannot be so inferred.

For formalized relexive associations, there are distinct classes representing 
the referring participant and the referred-to participant. For non-formalized  
reflexive associations this directionality between referring and referred-to 
classes is captured in the placement of the role phrases within two same-class 
instances in the meta-model data structure.

To support symmetric reflexive associations, placement of the single role 
phrase can be used to define the 'forward' direction - i.e from referring 
class to referred-to class; by convention, the phrase is stored in the 
referred-to representative.  Supressing any retention of a role phrase in 
the referring representative is a sufficient measure to distinguish the 
association as symmetric.

== 5 Work Required

The Association editor dialog should be modified to present a 'Symmetric' 
check box when, and only when, reflexive associations are selected for edit. 
When checked, the superfluous fields for the second role phrase, multiplicity 
selection and conditionality choice should be suppressed.

The relate, unrelate, and select logic must be enhanced to support the symmetric 
semantics described above.

The content assist feature must suppress non-role-phrase occurrences of symmetric 
associations in  proposal lists.

Verifier's display logic must provide missing role phrases where needed in 
Session Explorer, and should not display two 'directions' of a symmetric 
association when displaying instance variable data.

== 6 Acceptance Test

As this is a new feature enhancement, specific tests must be developed.


== 7 Document References

In this section, list all the documents that the reader may need to refer to.
Give the full path to reference a file.

. [[dr-1]] https://support.onefact.net/issues/12548]

---

This work is licensed under the Creative Commons CC0 License

---
