<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="maslBase" nsURI="http://www.xtuml.org/bp/xtext/masl/MASLbase"
    nsPrefix="maslBase">
  <eClassifiers xsi:type="ecore:EClass" name="AbstractNamed" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StateType">
    <eLiterals name="assigner" literal="assigner"/>
    <eLiterals name="assignerStart" value="1" literal="assignerStart"/>
    <eLiterals name="creation" value="2" literal="creation"/>
    <eLiterals name="terminal" value="3" literal="terminal"/>
  </eClassifiers>
</ecore:EPackage>
