/*
 * generated by Xtext 2.9.2
 */
package org.xtuml.bp.xtext.masl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MASLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtuml/bp/xtext/masl/parser/antlr/internal/InternalMASLParser.tokens");
	}
}
