#!/bin/ksh
#========================================================================
#
#File:      $RCSfile:$
#Version:   $Revision:$
#Modified:  $Date:$
#
#(c) Copyright 2005-2012 by Mentor Graphics Corp. All rights reserved.
#
#========================================================================
#This document contains information proprietary and confidential to
#Mentor Graphics Corp., and is not for external distribution.
#======================================================================== 
#
MGLS_LOC=/opt/phoenix/mgclm/exports.v7-1_0-3-1_engr-ss6
export MGLS_HOME=$MGLS_LOC/mgc_home/pkgs/mgls.ss6
export MGLS_LICENSE_FILE=$MGLS_LOC/mgc_home/licenses/license.dat
export LM_LICENSE_FILE=$MGLS_LICENSE_FILE 
#
$MGLS_HOME/bin/lmgrd -c $MGLS_LICENSE_FILE -l $MGLS_LOC/mgc_home/log/mgclm.log
