= Analysis of Inconsistent Event Displays

xtUML Project Analysis Note

== 1 Abstract

Customer finds the display of a polymorphic state model event and a
non-polymorphic instance event to be too inconsistent to be easily understood.
A more detailed description is given in the customer supplied document attached
to issue <<dr-1, 12504>>.

== 2 Introduction and Background

When polymorphic events were added to BridgePoint, a design decision was made to
make the labeling distinct from the non-polymorphic events. This design
decision is brought into question by this user request.

== 3 Requirements

A decision was made to make the supertype event labels consistent with the 
local events.

====
<Class Key Letters>:<Event Name><Event Number>( <parameters> )
====

The class key letters used are for the class in which the event is declared.

== 4 Analysis

The event display rendering is done in the class, _State Machine Event_, by the
method, _getName_. Changes to this method are reflected in models immediately.

Further work needs to be done to see if the iUML-based models are supported
correctly where they allow overriding a polymorphic event.

== 5 Work Required

. Modify the _getName_ method to meet the requirements.
. Update any tests that are dependent upon the current polymorphic event naming
convention.

== 6 Acceptance Test

Manual review of polymorphic events in models to ensure they meet requirements.

== 7 Document References

In this section, list all the documents that the reader may need to refer to.
Give the full path to reference a file.

. [[dr-1]] https://support.onefact.net/issues/12504[12504 - Display of local and polymorphic events on a state chart is inconstent]

---

This work is licensed under the Creative Commons CC0 License

---
