= Analysis of Inconsistent Event Displays

xtUML Project Analysis Note

== 1 Abstract

Customer finds the display of a polymorphic state model event and a
non-polymorphic instance event to be too inconsistent to be easily understood.
A more detailed description is given in the customer supplied document attached
to issue <<dr-1, 12504>>.

== 2 Introduction and Background

When polymorphic events were added to BridgePoint, a design decision was made to
make the labeling distinct from the non-polymorphic events. This design
decision is brought into question by this user request.

== 3 Requirements

A decision was made to make the supertype event labels consistent with the 
local events.

====
<SuperClass Key Letters>:<Event Name><Event Number>( <parameters> )
====

The class key letters used are for the class in which the event is declared.

== 4 Analysis

The event display rendering is done in the class, _State Machine Event_, by the
method, _getName_. Changes to this method are reflected in models immediately.

Further work needs to be done to see if the ASL and MASL models are supported
correctly where they allow concrete polymorphic events; the MASL documentation
for polymorphic events uses the superclass name as follows: "Polymorphic events
are not defined on the subtype, but referenced in the subtype's state
transition table by prefixing them with the supertype object name." This should
make them compatible with this change.

== 5 Work Required

. Modify the _getName_ method to meet the requirements.
. Modify any other methods that work with polymorphic events.
  e.g., SEM Event.migrateToLocalPoly
. Update any tests that are dependent upon the current polymorphic event naming
  convention.
. Ensure model compilation doesn't make any assumptions upon polymorphic event
  naming.
. Ensure MASL models work with the change.

== 6 Acceptance Test

. Manual review of polymorphic events in models to ensure they meet
  requirements.
. All tests pass.


== 7 Document References

In this section, list all the documents that the reader may need to refer to.
Give the full path to reference a file.

. [[dr-1]] https://support.onefact.net/issues/12504[12504 - Display of local and polymorphic events on a state chart is inconstent]

---

This work is licensed under the Creative Commons CC0 License

---
