.//=======================================================================
.//
.// File:      $RCSfile: gen_testClearDatabaseClass.arc,v $
.// Version:   $Revision: 1.19 $
.// Modified:  $Date: 2013/05/10 05:55:14 $
.//
.// (c) Copyright 2005-2014 by Mentor Graphics Corp.  All rights reserved.
.//
.//=======================================================================
.// Licensed under the Apache License, Version 2.0 (the "License"); you may not
.// use this file except in compliance with the License.  You may obtain a copy
.// of the License at
.//
.//      http://www.apache.org/licenses/LICENSE-2.0
.//
.// Unless required by applicable law or agreed to in writing, software
.// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
.// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   See the
.// License for the specific language governing permissions and limitations under
.// the License.
.//=======================================================================
.invoke arc_env = GET_ENV_VAR( "PTC_MC_ARC_DIR" )
.assign mc_archetypes = arc_env.result
.if ( mc_archetypes == "" )
  .print "\nERROR: Environment variable PTC_MC_ARC_DIR not set."
  .exit 100
.end if
.//
.include "${mc_archetypes}/arch_utils.inc"
.//
.function check_class_instance_list
  .param string ooaofgraphics_obj
  .param string instance_list_obj
.//      
  .select many classes from instances of O_OBJ
  .for each class in classes
    .if ("${class.Descrip:PEI}" != "true")
      .invoke cn = get_class_name(class)
		${instance_list_obj} = ${ooaofgraphics_obj}.getInstanceList(${cn.body}.class);
		assertTrue("The instances of ${cn.body} are not cleared", ${instance_list_obj}.isEmpty());            
    .end if
  .end for
.end function
.//
.assign file_name = "com.mentor.nucleus.bp.ui.canvas.test.I686ClearDatabaseTest.java"
//========================================================================
//
// File: ${file_name}
//
// WARNING:      Do not edit this generated file
// Generated by: ${info.arch_file_name}
// Version:      $$Revision: 1.19 $$
//
// (c) Copyright 2005-2014 by Mentor Graphics Corp.  All rights reserved.
//
//========================================================================
// Licensed under the Apache License, Version 2.0 (the "License"); you may not 
// use this file except in compliance with the License.  You may obtain a copy 
// of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software 
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT 
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   See the 
// License for the specific language governing permissions and limitations under
// the License.
//======================================================================== 
package com.mentor.nucleus.bp.ui.canvas.test;

import org.eclipse.core.resources.IFile;
import org.eclipse.core.runtime.CoreException;
import org.eclipse.core.runtime.NullProgressMonitor;

import com.mentor.nucleus.bp.core.common.ClassQueryInterface_c;
import com.mentor.nucleus.bp.core.common.InstanceList;
import com.mentor.nucleus.bp.core.Ooaofooa;
import com.mentor.nucleus.bp.core.Package_c;
import com.mentor.nucleus.bp.test.common.BaseTest;
import com.mentor.nucleus.bp.test.common.TestingUtilities;
import com.mentor.nucleus.bp.ui.canvas.*;

public class I686ClearDatabaseTest extends BaseTest{

	static IFile model = null;
	static Ooaofooa modelRoot = getDefaultTestInstance();
	
	public I686ClearDatabaseTest(String name) throws Exception {
		super("clearDatabase", name); //$$NON-NLS-1$$
	}
	
	public I686ClearDatabaseTest(String projectName, String name) throws CoreException {
		super("clearDatabase", name);	//$$NON-NLS-1$$
	}
	
	protected void setUp() throws Exception {
		super.setUp();
		// load test model
		TestingUtilities.importTestingProjectIntoWorkspace("canvastest");
		BaseTest.dispatchEvents(0);
		m_sys = getSystemModel("canvastest");
		modelRoot = (Ooaofooa) Package_c.getOneEP_PKGOnR1401(m_sys,
				new ClassQueryInterface_c() {

					@Override
					public boolean evaluate(Object candidate) {
						return ((Package_c) candidate).getName().equals(
								"canvastest");
					}
				}).getModelRoot();
	}
	
	public void testClearDatabase(){
		modelRoot.clearDatabase(new NullProgressMonitor());
		Ooaofgraphics ooaofgraphics = Ooaofgraphics.getInstance(modelRoot.getId());
		
		InstanceList list = null;
		
		.invoke check_instance_list = check_class_instance_list("ooaofgraphics", "list");
		${check_instance_list.body}
	}
}

.emit to file "src/com/mentor/nucleus/bp/ui/canvas/test/I686ClearDatabaseTest.java"