/**
 * generated by Xtext 2.9.2
 */
package org.xtuml.bp.xtext.masl.masl.behavior;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Case Others</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtuml.bp.xtext.masl.masl.behavior.BehaviorPackage#getCaseOthers()
 * @model
 * @generated
 */
public interface CaseOthers extends StatementList {
} // CaseOthers
