/**
 * generated by Xtext 2.9.2
 */
package org.xtuml.bp.xtext.masl.masl.behavior;

import org.xtuml.bp.xtext.masl.masl.structure.AbstractFeature;
import org.xtuml.bp.xtext.masl.masl.structure.AbstractNamed;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Loop Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtuml.bp.xtext.masl.masl.behavior.BehaviorPackage#getLoopVariable()
 * @model
 * @generated
 */
public interface LoopVariable extends AbstractNamed, AbstractFeature {
} // LoopVariable
