/**
 * generated by Xtext 2.9.2
 */
package org.xtuml.bp.xtext.masl.masl.behavior.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtuml.bp.xtext.masl.masl.behavior.BehaviorPackage;
import org.xtuml.bp.xtext.masl.masl.behavior.DefaultExceptionHandler;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Default Exception Handler</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DefaultExceptionHandlerImpl extends StatementListImpl implements DefaultExceptionHandler {
	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DefaultExceptionHandlerImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return BehaviorPackage.Literals.DEFAULT_EXCEPTION_HANDLER;
	}

} //DefaultExceptionHandlerImpl
