/**
 * generated by Xtext 2.9.2
 */
package org.xtuml.bp.xtext.masl.masl.types;

import org.xtuml.bp.xtext.masl.masl.behavior.ConstExpression;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Delta Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtuml.bp.xtext.masl.masl.types.DeltaConstraint#getDelta <em>Delta</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.masl.types.DeltaConstraint#getConstraint <em>Constraint</em>}</li>
 * </ul>
 *
 * @see org.xtuml.bp.xtext.masl.masl.types.TypesPackage#getDeltaConstraint()
 * @model
 * @generated
 */
public interface DeltaConstraint extends AbstractTypeConstraint {
	/**
	 * Returns the value of the '<em><b>Delta</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Delta</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Delta</em>' containment reference.
	 * @see #setDelta(ConstExpression)
	 * @see org.xtuml.bp.xtext.masl.masl.types.TypesPackage#getDeltaConstraint_Delta()
	 * @model containment="true"
	 * @generated
	 */
	ConstExpression getDelta();

	/**
	 * Sets the value of the '{@link org.xtuml.bp.xtext.masl.masl.types.DeltaConstraint#getDelta <em>Delta</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Delta</em>' containment reference.
	 * @see #getDelta()
	 * @generated
	 */
	void setDelta(ConstExpression value);

	/**
	 * Returns the value of the '<em><b>Constraint</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Constraint</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Constraint</em>' containment reference.
	 * @see #setConstraint(RangeConstraint)
	 * @see org.xtuml.bp.xtext.masl.masl.types.TypesPackage#getDeltaConstraint_Constraint()
	 * @model containment="true"
	 * @generated
	 */
	RangeConstraint getConstraint();

	/**
	 * Sets the value of the '{@link org.xtuml.bp.xtext.masl.masl.types.DeltaConstraint#getConstraint <em>Constraint</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Constraint</em>' containment reference.
	 * @see #getConstraint()
	 * @generated
	 */
	void setConstraint(RangeConstraint value);

} // DeltaConstraint
