/**
 * generated by Xtext 2.9.2
 */
package org.xtuml.bp.xtext.masl.masl.types;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dictionary Type Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtuml.bp.xtext.masl.masl.types.DictionaryTypeReference#getKeyType <em>Key Type</em>}</li>
 * </ul>
 *
 * @see org.xtuml.bp.xtext.masl.masl.types.TypesPackage#getDictionaryTypeReference()
 * @model
 * @generated
 */
public interface DictionaryTypeReference extends AbstractCollectionTypeReference {
	/**
	 * Returns the value of the '<em><b>Key Type</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Key Type</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Key Type</em>' containment reference.
	 * @see #setKeyType(AbstractTypeReference)
	 * @see org.xtuml.bp.xtext.masl.masl.types.TypesPackage#getDictionaryTypeReference_KeyType()
	 * @model containment="true"
	 * @generated
	 */
	AbstractTypeReference getKeyType();

	/**
	 * Sets the value of the '{@link org.xtuml.bp.xtext.masl.masl.types.DictionaryTypeReference#getKeyType <em>Key Type</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Key Type</em>' containment reference.
	 * @see #getKeyType()
	 * @generated
	 */
	void setKeyType(AbstractTypeReference value);

} // DictionaryTypeReference
