<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="oAL"
    nsURI="http://www.argouml.org/xtuml/OAL" nsPrefix="oAL">
  <eClassifiers xsi:type="ecore:EClass" name="Code">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.xtuml.bp.ui.text/src-gen/org/argouml/xtuml/OAL.ecore#//statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="st1" eType="ecore:EClass platform:/resource/org.xtuml.bp.ui.text/src-gen/org/argouml/xtuml/OAL.ecore#//assignment"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="st2" eType="ecore:EClass platform:/resource/org.xtuml.bp.ui.text/src-gen/org/argouml/xtuml/OAL.ecore#//TypeObjectStatement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="st3" eType="ecore:EClass platform:/resource/org.xtuml.bp.ui.text/src-gen/org/argouml/xtuml/OAL.ecore#//TypeStatement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeObjectStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="select_statement" eSuperTypes="platform:/resource/org.xtuml.bp.ui.text/src-gen/org/argouml/xtuml/OAL.ecore#//TypeObjectStatement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="var" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="assignment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="e" eType="ecore:EClass platform:/resource/org.xtuml.bp.ui.text/src-gen/org/argouml/xtuml/OAL.ecore#//expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="substatements" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.xtuml.bp.ui.text/src-gen/org/argouml/xtuml/OAL.ecore#//statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="expression" eSuperTypes="platform:/resource/org.xtuml.bp.ui.text/src-gen/org/argouml/xtuml/OAL.ecore#//select_statement platform:/resource/org.xtuml.bp.ui.text/src-gen/org/argouml/xtuml/OAL.ecore#//TypeValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ne" eType="ecore:EClass platform:/resource/org.xtuml.bp.ui.text/src-gen/org/argouml/xtuml/OAL.ecore#//expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ls" eType="ecore:EClass platform:/resource/org.xtuml.bp.ui.text/src-gen/org/argouml/xtuml/OAL.ecore#//expr2"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rs" upperBound="-1" eType="ecore:EClass platform:/resource/org.xtuml.bp.ui.text/src-gen/org/argouml/xtuml/OAL.ecore#//expr2"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="expr2">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="n" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="s" eType="ecore:EClass platform:/resource/org.xtuml.bp.ui.text/src-gen/org/argouml/xtuml/OAL.ecore#//sum"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="sum">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lt" eType="ecore:EClass platform:/resource/org.xtuml.bp.ui.text/src-gen/org/argouml/xtuml/OAL.ecore#//product"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rt" upperBound="-1" eType="ecore:EClass platform:/resource/org.xtuml.bp.ui.text/src-gen/org/argouml/xtuml/OAL.ecore#//product"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="product">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lf" eType="ecore:EClass platform:/resource/org.xtuml.bp.ui.text/src-gen/org/argouml/xtuml/OAL.ecore#//TypeValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rf" upperBound="-1" eType="ecore:EClass platform:/resource/org.xtuml.bp.ui.text/src-gen/org/argouml/xtuml/OAL.ecore#//TypeValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypeCreate" eSuperTypes="platform:/resource/org.xtuml.bp.ui.text/src-gen/org/argouml/xtuml/OAL.ecore#//TypeObjectStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypeRelate" eSuperTypes="platform:/resource/org.xtuml.bp.ui.text/src-gen/org/argouml/xtuml/OAL.ecore#//TypeObjectStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypeDelete" eSuperTypes="platform:/resource/org.xtuml.bp.ui.text/src-gen/org/argouml/xtuml/OAL.ecore#//TypeObjectStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypeStatementIf" eSuperTypes="platform:/resource/org.xtuml.bp.ui.text/src-gen/org/argouml/xtuml/OAL.ecore#//TypeStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="ecore:EClass platform:/resource/org.xtuml.bp.ui.text/src-gen/org/argouml/xtuml/OAL.ecore#//expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elifexpr" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.xtuml.bp.ui.text/src-gen/org/argouml/xtuml/OAL.ecore#//expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeStatementFor" eSuperTypes="platform:/resource/org.xtuml.bp.ui.text/src-gen/org/argouml/xtuml/OAL.ecore#//TypeStatement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="list" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeStatementWhile" eSuperTypes="platform:/resource/org.xtuml.bp.ui.text/src-gen/org/argouml/xtuml/OAL.ecore#//TypeStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="ecore:EClass platform:/resource/org.xtuml.bp.ui.text/src-gen/org/argouml/xtuml/OAL.ecore#//expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeValueVariable" eSuperTypes="platform:/resource/org.xtuml.bp.ui.text/src-gen/org/argouml/xtuml/OAL.ecore#//TypeValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypeConstant" eSuperTypes="platform:/resource/org.xtuml.bp.ui.text/src-gen/org/argouml/xtuml/OAL.ecore#//TypeValue"/>
</ecore:EPackage>
