--
--======================================================================
--
-- File:      $RCSfile: context_menu.pei.sql,v $
-- Version:   $Revision: 1.68 $
-- Modified:  $Date: 2013/05/12 22:30:47 $
--
-- (c) Copyright 2003-2014 Mentor Graphics Corporation All rights reserved.
--
--======================================================================
-- Licensed under the Apache License, Version 2.0 (the "License"); you may not 
-- use this file except in compliance with the License.  You may obtain a copy 
-- of the License at
--
--   http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software 
-- distributed under the License is distributed on an "AS IS" BASIS, WITHOUT 
-- WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   See the 
-- License for the specific language governing permissions and limitations under
-- the License.
--======================================================================
--
--                     Specialism   Label                    Key_Lett   Resultant Class    Global
INSERT INTO CME VALUES ('Delete', '',                         'S_SYS',    '',              true );
INSERT INTO CME VALUES ('Rename', '',                         'S_SYS',    '',              true );
INSERT INTO CME VALUES ('New','Package',                      'S_SYS', 'EP_PKG',           false, '', '', false, '', false, false, '' ,'->EP_PKG[R1401]');
INSERT INTO CME VALUES ('Delete', '',                         'S_DOM', '',                 true );
INSERT INTO CME VALUES ('Rename', '',                         'S_DOM', '',                 true );
INSERT INTO CME VALUES ('Delete', '',                         'CL_IC', '',                 true );
INSERT INTO CME VALUES ('Specialized Package',   'Assign Component',         'CL_IC', '',                 false, 'Choose the component to reference' );
INSERT INTO CME VALUES ('',       'Unassign',                 'CL_IC', '',                 false, '', '*');
INSERT INTO CME VALUES ('Delete', '',                         'CP_CP', '',                 true );
INSERT INTO CME VALUES ('Rename', '',                         'CP_CP', '',                 true );
INSERT INTO CME VALUES ('New', 'Component',                   'CP_CP', 'C_C',              false);
INSERT INTO CME VALUES ('New', 'Component Reference'    ,      'CP_CP', 'CL_IC',           false);
INSERT INTO CME VALUES ('Delete', '',                         'IP_IP', '',                 true );
INSERT INTO CME VALUES ('Rename', '',                         'IP_IP', '',                 true );
INSERT INTO CME VALUES ('New', 'Interface'    ,               'IP_IP', 'C_I',              false);
INSERT INTO CME VALUES ('Delete', '',                         'C_C',   '',                 true );
INSERT INTO CME VALUES ('Rename', '',                         'C_C',   '',                 true );
INSERT INTO CME VALUES ('New',    'Package',                  'C_C',   'EP_PKG',           false , '', '', false, '', false, false, '' ,'->PE_PE[R8003]->EP_PKG[R8001]');
INSERT INTO CME VALUES ('New',    'Component',                'C_C',   'C_C',              false , '', '', false, '', false, false, '' ,'->PE_PE[R8003]->C_C[R8001]');
INSERT INTO CME VALUES ('New',    'Component Reference',      'C_C',   'CL_IC',            false);
INSERT INTO CME VALUES ('Delete', '',                         'C_I',   '',                 true );
INSERT INTO CME VALUES ('Rename', '',                         'C_I',   '',                 true );
INSERT INTO CME VALUES ('Delete', '',                         'C_P',   '',                 true );
INSERT INTO CME VALUES ('Rename', '',                         'C_P',   '',                 true );
INSERT INTO CME VALUES ('Delete', '',                         'C_R',   '',                 true );
INSERT INTO CME VALUES ('Rename', '',                         'C_R',   '',                 true );
INSERT INTO CME VALUES ('Delete', '',                         'C_PO',  '',                 true );
INSERT INTO CME VALUES ('Rename', '',                         'C_PO',  '',                 true );
INSERT INTO CME VALUES ('New', 'Signal',                      'C_I',   'C_AS',             false , '', '', false, '', false, false, '' ,'->C_EP[R4003]->C_AS[R4004]');
INSERT INTO CME VALUES ('New', 'Operation',                   'C_I',   'C_IO',             false , '', '', false, '', false, false, '' ,'->C_EP[R4003]->C_IO[R4004]');
INSERT INTO CME VALUES ('Delete', '',                         'C_AS',  '',                 true );
INSERT INTO CME VALUES ('Rename', '',                         'C_AS',  '',                 true );
INSERT INTO CME VALUES ('Delete', '',                         'C_IO',  '',                 true );
INSERT INTO CME VALUES ('Rename', '',                         'C_IO',  '',                 true );
INSERT INTO CME VALUES ('New', 'Parameter',                   'C_IO',  'C_PP',             false, '', '', false, '', false, false, '' ,'->C_EP[R4004]->C_PP[R4006]');
INSERT INTO CME VALUES ('New', 'Parameter',                   'C_AS',  'C_PP',             false, '', '', false, '', false, false, '' ,'->C_EP[R4004]->C_PP[R4006]');
INSERT INTO CME VALUES ('Delete', '',                         'C_PP',  '',                 true );
INSERT INTO CME VALUES ('Rename', '',                         'C_PP',  '',                 true );
INSERT INTO CME VALUES ('Component',          'Formalize',    'C_C',   '', false, 'Choose the domain that should describe the structure of this component' );
INSERT INTO CME VALUES ('Specialized Package Provided Interface', 'Formalize',  'C_P',   '', false, 'Choose the defined interface that this interface reference shall represent' );
INSERT INTO CME VALUES ('Generic Package',     'Formalize',  'C_P',   'C_I', false, 'Choose the defined interface that this interface reference shall represent', '*', false, '', true, false, 'interface' );
INSERT INTO CME VALUES ('Provided Interface',                     'Unformalize','C_P',   '', false, '', '*' );
INSERT INTO CME VALUES ('Specialized Package Required Interface', 'Formalize',  'C_R',   '', false, 'Choose the defined interface that this interface reference shall represent' );
INSERT INTO CME VALUES ('Generic Package',     'Formalize',  'C_R',   'C_I', false, 'Choose the defined interface that this interface reference shall represent', '*', false, '', true, false, 'interface' );
INSERT INTO CME VALUES ('Required Interface',                     'Unformalize','C_R',   '', false, '', '*' );
INSERT INTO CME VALUES ('Delete', '',                         'C_DG',  '',                 true );
INSERT INTO CME VALUES ('Delete', '',                         'SQ_S',  '',                 true );
INSERT INTO CME VALUES ('Rename', '',                         'SQ_S',  '',                 true );
INSERT INTO CME VALUES ('New', 'Component Participant',       'SQ_S',  'SQ_COP',           false );
INSERT INTO CME VALUES ('New', 'Instance',                    'SQ_S',  'SQ_CIP',           false );
INSERT INTO CME VALUES ('New', 'Actor Participant',           'SQ_S',  'SQ_AP',            false );
INSERT INTO CME VALUES ('New', 'External Entity',             'SQ_S',  'SQ_EEP',           false );
INSERT INTO CME VALUES ('New', 'Class Participant',           'SQ_S',  'SQ_CP',            false );
INSERT INTO CME VALUES ('Delete', '',                         'SQ_CP', '',                 true );
INSERT INTO CME VALUES ('Rename', '',                         'SQ_CP', '',                 true );
INSERT INTO CME VALUES ('Delete', '',                         'MSG_A', '',                 true );
INSERT INTO CME VALUES ('Rename', '',                         'MSG_A', '',                 true );
INSERT INTO CME VALUES ('Delete', '',                         'SQ_COP','',                 true );
INSERT INTO CME VALUES ('Rename', '',                         'SQ_COP','',                 true );
INSERT INTO CME VALUES ('Delete', '',                         'SQ_AV', '',                 true );
INSERT INTO CME VALUES ('Rename', '',                         'SQ_AV', '',                 true );
INSERT INTO CME VALUES ('Delete', '',                         'SQ_CPA','',                 true );
INSERT INTO CME VALUES ('Rename', '',                         'SQ_CPA','',                 true );
INSERT INTO CME VALUES ('Delete', '',                         'SQ_EEP','',                 true );
INSERT INTO CME VALUES ('Rename', '',                         'SQ_EEP','',                 true );
INSERT INTO CME VALUES ('Delete', '',                         'SQ_FPP','',                 true );
INSERT INTO CME VALUES ('Rename', '',                         'SQ_FPP','',                 true );
INSERT INTO CME VALUES ('Delete', '',                         'SQ_CIP','',                 true );
INSERT INTO CME VALUES ('Rename', '',                         'SQ_CIP','',                 true );
INSERT INTO CME VALUES ('Delete', '',                         'SQ_LS', '',                 true );
INSERT INTO CME VALUES ('Delete', '',                         'MSG_R', '',                 true );
INSERT INTO CME VALUES ('Rename', '',                         'MSG_R', '',                 true );
INSERT INTO CME VALUES ('Delete', '',                         'MSG_SM','',                 true );
INSERT INTO CME VALUES ('Rename', '',                         'MSG_SM','',                 true );
INSERT INTO CME VALUES ('Delete', '',                         'MSG_AM','',                 true );
INSERT INTO CME VALUES ('Rename', '',                         'MSG_AM','',                 true );
INSERT INTO CME VALUES ('Delete', '',                         'SQ_TM', '',                 true );
INSERT INTO CME VALUES ('Rename', '',                         'SQ_TM', '',                 true );
INSERT INTO CME VALUES ('Delete', '',                         'SQ_TS', '',                 true );
INSERT INTO CME VALUES ('Rename', '',                         'SQ_TS', '',                 true );
INSERT INTO CME VALUES ('Delete', '',                         'SQ_AP', '',                 true );
INSERT INTO CME VALUES ('Rename', '',                         'SQ_AP', '',                 true );
INSERT INTO CME VALUES ('Delete', '',                         'SQ_PP', '',                 true );
INSERT INTO CME VALUES ('Rename', '',                         'SQ_PP', '',                 true );
INSERT INTO CME VALUES ('Delete', '',                         'S_DPK', '',                 true );
INSERT INTO CME VALUES ('Rename', '',                         'S_DPK', '',                 true );
INSERT INTO CME VALUES ('New', 'User DataType',               'S_DPK', 'S_UDT',            false);
INSERT INTO CME VALUES ('New', 'Structured DataType',         'S_DPK', 'S_SDT',            false);
INSERT INTO CME VALUES ('New', 'Enumeration DataType',        'S_DPK', 'S_EDT',            false);
INSERT INTO CME VALUES ('New', 'Constant Specification',      'S_DPK', 'CNST_CSP',         false);
INSERT INTO CME VALUES ('Delete', '',                         'S_UDT', '',                 true );
INSERT INTO CME VALUES ('Rename', '',                         'S_UDT', '',                 true );
INSERT INTO CME VALUES ('Delete', '',                         'S_EDT', '',                 true );
INSERT INTO CME VALUES ('Rename', '',                         'S_EDT', '',                 true );
INSERT INTO CME VALUES ('New',    'Enumerator',               'S_EDT', 'S_ENUM',           false , '', '', false, '', false, false, '' ,'->S_ENUM[R27]');
INSERT INTO CME VALUES ('Delete', '',                   'S_ENUM',   '',                      true );
INSERT INTO CME VALUES ('Rename', '',                   'S_ENUM',   '',                      true );
INSERT INTO CME VALUES ('Delete', '',                   'CNST_CSP', '',                      true );
INSERT INTO CME VALUES ('Rename', '',                   'CNST_CSP', '',                      true );
INSERT INTO CME VALUES ('New',    'Constant',           'CNST_CSP', 'CNST_LSC',              false , '', '', false, '', false, false, '' ,'->CNST_SYC[R1504]->CNST_LFSC[R1502]->CNST_LSC[R1503]');
INSERT INTO CME VALUES ('Delete', '',                   'CNST_LSC',   '',                    true );
INSERT INTO CME VALUES ('Rename', '',                   'CNST_LSC',   '',                    true );
INSERT INTO CME VALUES ('Delete', '',                   'S_FPK',    '',                      true );
INSERT INTO CME VALUES ('Rename', '',                   'S_FPK',    '',                      true );
INSERT INTO CME VALUES ('New',    'Function',           'S_FPK',    'S_SYNC',                false);
INSERT INTO CME VALUES ('Delete', '',                   'S_SYNC',   '',                      true );
INSERT INTO CME VALUES ('Rename', '',                   'S_SYNC',   '',                      true );
INSERT INTO CME VALUES ('New',    'Parameter',          'S_SYNC',   'S_SPARM',               false, '', '', false, '', false, false, '' ,'->S_SPARM[R24]');
INSERT INTO CME VALUES ('Delete', '',                   'S_SPARM',  '',                      true );
INSERT INTO CME VALUES ('Rename', '',                   'S_SPARM',  '',                      true );
INSERT INTO CME VALUES ('Delete', '',                   'S_EEPK',    '',                     true );
INSERT INTO CME VALUES ('Rename', '',                   'S_EEPK',    '',                     true );
INSERT INTO CME VALUES ('New',    'External Entity',    'S_EEPK',    'S_EE',                 false );
INSERT INTO CME VALUES ('Delete', '',                   'S_EE',      '',                     true );
INSERT INTO CME VALUES ('Rename', '',                   'S_EE',      '',                     true );
INSERT INTO CME VALUES ('New',    'Bridge Operation',   'S_EE',      'S_BRG',                false, '', '', false, '', false, false, '' ,'->S_BRG[R19]');
INSERT INTO CME VALUES ('Delete', '',                   'S_BRG',     '',                     true );
INSERT INTO CME VALUES ('Rename', '',                   'S_BRG',     '',                     true );
INSERT INTO CME VALUES ('New',    'Parameter',          'S_BRG',    'S_BPARM',               false, '', '', false, '', false, false, '' ,'->S_BPARM[R21]');
INSERT INTO CME VALUES ('Delete', '',                   'S_BPARM',  '',                      true );
INSERT INTO CME VALUES ('Rename', '',                   'S_BPARM',  '',                      true );
INSERT INTO CME VALUES ('Delete', '',                   'S_SS',     '',                      true );
INSERT INTO CME VALUES ('Rename', '',                   'S_SS',     '',                      true );
INSERT INTO CME VALUES ('New', 'Class',                 'S_SS',     'O_OBJ',                 false );
INSERT INTO CME VALUES ('New', 'Imported Class',        'S_SS',     'O_IOBJ',                false );
INSERT INTO CME VALUES ('Delete', '',                   'O_OBJ',    '',                      true );
INSERT INTO CME VALUES ('Rename', '',                   'O_OBJ',    '',                      true );
INSERT INTO CME VALUES ('New',    'Attribute',          'O_OBJ',    'O_ATTR',                false, '', '', false, '', false, false, '' ,'->O_ATTR[R102]');
INSERT INTO CME VALUES ('Delete', '',                   'O_ATTR',    '',                     true );
INSERT INTO CME VALUES ('Rename', '',                   'O_ATTR',    '',                     true );
INSERT INTO CME VALUES ('New',    'Operation',          'O_OBJ',    'O_TFR',                 false, '', '', false, '', false, false, '' ,'->O_TFR[R115]');
INSERT INTO CME VALUES ('Delete', '',                   'O_TFR',    '',                      true );
INSERT INTO CME VALUES ('Rename', '',                   'O_TFR',    '',                      true );
INSERT INTO CME VALUES ('New',    'Parameter',          'O_TFR',    'O_TPARM',               false, '', '', false, '', false, false, '' ,'->O_TPARM[R117]');
INSERT INTO CME VALUES ('Delete', '',                   'O_TPARM',  '',                      true );
INSERT INTO CME VALUES ('Rename', '',                   'O_TPARM',  '',                      true );
INSERT INTO CME VALUES ('New',    'Instance State Machine','O_OBJ', 'SM_ISM',                false);
INSERT INTO CME VALUES ('Delete', '',                   'SM_ISM',   '',                      true );
INSERT INTO CME VALUES ('New',    'Event',              'SM_ISM',   'SM_EVT',                false, '', '', false, '', false, false, '' ,'->SM_SM[R517]->SM_EVT[R502]');
INSERT INTO CME VALUES ('New',    'State',              'SM_ISM',   'SM_STATE',              false, '', '', false, '', false, false, '' ,'->SM_SM[R517]->SM_STATE[R501]');
INSERT INTO CME VALUES ('Delete', '',                   'SM_NLEVT', '',                      true );
INSERT INTO CME VALUES ('Delete', '',                   'SM_EVT',   '',                      true );
INSERT INTO CME VALUES ('Rename', '',                   'SM_EVT',   '',                      true );
INSERT INTO CME VALUES ('Delete', '',                   'SM_EVTDI', '',                      true );
INSERT INTO CME VALUES ('Rename', '',                   'SM_EVTDI', '',                      true );
INSERT INTO CME VALUES ('New',    'Class State Machine','O_OBJ',    'SM_ASM',                false);
INSERT INTO CME VALUES ('Delete', '',                   'SM_ASM',   '',                      true );
INSERT INTO CME VALUES ('New',    'Event',              'SM_ASM',   'SM_EVT',                false, '', '', false, '', false, false, '' ,'->SM_SM[R517]->SM_EVT[R502]');
INSERT INTO CME VALUES ('New',    'State',              'SM_ASM',   'SM_STATE',              false, '', '', false, '', false, false, '' ,'->SM_SM[R517]->SM_STATE[R501]');
INSERT INTO CME VALUES ('Delete', '',                   'SM_STATE', '',                      true );
INSERT INTO CME VALUES ('Rename', '',                   'SM_STATE', '',                      true );
INSERT INTO CME VALUES ('Delete', '',					'O_IOBJ',	'',						 true );
INSERT INTO CME VALUES ('Delete', '',					'R_REL',	'',						 true );
INSERT INTO CME VALUES ('Delete', '',					'SM_TXN',	'',						 true );
INSERT INTO CME VALUES ('Delete', '',					'SM_CRTXN',	'',						 true );
INSERT INTO CME VALUES ('Delete', '',					'R_ASSR',	'',						 true );
INSERT INTO CME VALUES ('Delete', '',					'R_SUB',	'',						 true );
INSERT INTO CME VALUES ('',       'Add to Identifier',  'O_ATTR',   '',                      false, 'Select identifier to add this attribute to' );
INSERT INTO CME VALUES ('',   'Remove from Identifier', 'O_ATTR',   '',                      false, 'Select identifier to remove this attribute from' );
INSERT INTO CME VALUES ('',  'Set as Derived Attribute','O_ATTR',   '',                      false, '' );
INSERT INTO CME VALUES ('',     'Set as Base Attribute','O_ATTR',   '',                      false );
INSERT INTO CME VALUES ('',       'Move Up',            'O_ATTR',   '',                      false, '' );
INSERT INTO CME VALUES ('',       'Move Down',          'O_ATTR',   '',                      false, '' );
INSERT INTO CME VALUES ('',       'Combine With',       'O_ATTR',   '',                      false, 'Select attribute to combine with this one' );
INSERT INTO CME VALUES ('',       'Split',              'O_ATTR',   '',                      false, 'Select reference to split from this one' );
INSERT INTO CME VALUES ('Specialized Package',       'Assign Class',       'O_IOBJ',   '',        false, 'Select class this imported class represents' );
INSERT INTO CME VALUES ('Binary',     'Formalize',      'R_REL',    '',                      false, 'Select the class whose identifier will be used to formalize the association' );
INSERT INTO CME VALUES ('Linked',     'Formalize',      'R_REL',    '',                      false, 'Select the identifier to use from each class' );
INSERT INTO CME VALUES ('Linked',     'Formalize',      'R_ASSR',   '',                      false, 'Select the identifier to use from each class' );
INSERT INTO CME VALUES ('Inheritance','Formalize',      'R_REL',    '',                      false, 'Select identifier to use in supertype' );
INSERT INTO CME VALUES ('Inheritance','Formalize',      'R_SUB',    '',                      false, 'Select identifier to use in supertype' );
INSERT INTO CME VALUES ('',       'Unformalize',        'R_REL',    '',                      false, '' );
INSERT INTO CME VALUES ('',       'Unformalize',        'R_ASSR',   '',                      false, '' );
INSERT INTO CME VALUES ('',       'Unformalize',        'R_SUB',    '',                      false, '' );
INSERT INTO CME VALUES ('Specialized Package',   'Assign Event',       'SM_TXN',   '',                      false, 'Select event to assign to transition' );
INSERT INTO CME VALUES ('Generic Package',       'Assign Event',       'SM_TXN',   '',                      false, 'Select event to assign to transition' );
INSERT INTO CME VALUES ('Specialized Package',   'Assign Signal',      'SM_TXN',   '',                      false, 'Select signal to assign to transition' );
INSERT INTO CME VALUES ('Generic Package',       'Assign Signal',      'SM_TXN',   '',                      false, 'Select signal to assign to transition' );
INSERT INTO CME VALUES ('',       'Remove Event',       'SM_TXN',   '',                      false, '' );
INSERT INTO CME VALUES ('',       'Remove Signal',      'SM_TXN',   '',                      false, '' );
INSERT INTO CME VALUES ('Specialized Package',   'Assign Event',       'SM_CRTXN', '',                      false, 'Select event to assign to transition' );
INSERT INTO CME VALUES ('Generic Package',       'Assign Event',       'SM_CRTXN', '',                      false, 'Select event to assign to transition' );
INSERT INTO CME VALUES ('',       'Remove Event',       'SM_CRTXN', '',                      false, '' );
INSERT INTO CME VALUES ('Specialized Package',   'Ignore in State',      'SM_EVT',   '',     false, 'Select state where this event is ignored' );
INSERT INTO CME VALUES ('Generic Package',       'Ignore in State',      'SM_EVT',   '',     false, 'Select state where this event is ignored' );
INSERT INTO CME VALUES ('Specialized Package',   'Cant Happen in State', 'SM_EVT',   '',     false, 'Select state where this event can''t happen' );
INSERT INTO CME VALUES ('Generic Package',       'Cant Happen in State', 'SM_EVT',   '',     false, 'Select state where this event can''t happen' );
INSERT INTO CME VALUES ('Specialized Package',   'Ignore Event',       'SM_STATE', '',                      false, 'Select event to ignore in this state' );
INSERT INTO CME VALUES ('Generic Package',       'Ignore Event',       'SM_STATE', '',                      false, 'Select event to ignore in this state' );
INSERT INTO CME VALUES ('Specialized Package',   'Cant Happen Event',  'SM_STATE', '',                      false, 'Select event that can''t happen in this state' );
INSERT INTO CME VALUES ('Generic Package',       'Cant Happen Event',  'SM_STATE', '',                      false, 'Select event that can''t happen in this state' );
INSERT INTO CME VALUES ('New',    'Parameter',          'SM_EVT',   'SM_EVTDI',              false, '', '', false, '', false, false, '' ,'->SM_EVTDI[R532]');
INSERT INTO CME VALUES ('Delete', '',                   'COMM_COMM','',                      true );
INSERT INTO CME VALUES ('Rename', '',                   'COMM_COMM','',                      true );
INSERT INTO CME VALUES ('New', 'Component Participant', 'COMM_COMM','SQ_COP',                false );
INSERT INTO CME VALUES ('New', 'Instance',              'COMM_COMM','SQ_CIP',                false );
INSERT INTO CME VALUES ('New', 'Actor Participant',     'COMM_COMM','SQ_AP',                 false );
INSERT INTO CME VALUES ('New', 'External Entity',       'COMM_COMM','SQ_EEP',                false );
INSERT INTO CME VALUES ('New', 'Class Participant',     'COMM_COMM','SQ_CP',                 false );
INSERT INTO CME VALUES ('Delete', '',                   'COMM_LNK', '',                      true );
INSERT INTO CME VALUES ('Delete', '',                   'UC_UCC',   '',                      true );
INSERT INTO CME VALUES ('Rename', '',                   'UC_UCC',   '',                      true );
INSERT INTO CME VALUES ('New',    'Use Case diagram',   'UC_UCC',   'UC_UCC',                false );
INSERT INTO CME VALUES ('New',    'Usecase',            'UC_UCC',   'IA_UCP',                false );
INSERT INTO CME VALUES ('New',    'Actor',              'UC_UCC',   'SQ_AP',                 false );
INSERT INTO CME VALUES ('Delete', '',                   'IA_UCP',   '',                      true );
INSERT INTO CME VALUES ('Rename', '',                   'IA_UCP',   '',                      true );
INSERT INTO CME VALUES ('Delete', '',                   'UC_BA',    '',                      true );
INSERT INTO CME VALUES ('Delete', '',                   'UC_G',     '',                      true );
INSERT INTO CME VALUES ('Delete', '',                   'UC_I',     '',                      true );
INSERT INTO CME VALUES ('Delete', '',                   'UC_E',     '',                      true );
INSERT INTO CME VALUES ('Delete', '',                   'A_A',      '',                      true );
INSERT INTO CME VALUES ('Rename', '',                   'A_A',      '',                      true );
INSERT INTO CME VALUES ('New', 'Action',                'A_A',      'A_ACT',                 false );
INSERT INTO CME VALUES ('New', 'Object Node',           'A_A',      'A_OBJ',                 false );
INSERT INTO CME VALUES ('New', 'Accept Event Action',   'A_A',      'A_AEA',                 false );
INSERT INTO CME VALUES ('New', 'Send Signal Action',    'A_A',      'A_SS',                  false );
INSERT INTO CME VALUES ('New','Accept Time Event Action','A_A',     'A_ATE',                 false );
INSERT INTO CME VALUES ('Delete', '',                   'A_FJ',     '',                      true );
INSERT INTO CME VALUES ('Rename', '',                   'A_FJ',     '',                      true );
INSERT INTO CME VALUES ('Delete', '',                   'A_INI',    '',                      true );
INSERT INTO CME VALUES ('Delete', '',                   'A_E',      '',                      true );
INSERT INTO CME VALUES ('Rename', '',                   'A_E',      '',                      true );
INSERT INTO CME VALUES ('Delete', '',                   'A_AF',     '',                      true );
INSERT INTO CME VALUES ('Delete', '',                   'A_FF',     '',                      true );
INSERT INTO CME VALUES ('Rename', '',                   'A_GA',     '',                      true );
INSERT INTO CME VALUES ('Delete', '',                   'A_GA',     '',                      true );
INSERT INTO CME VALUES ('Rename', '',                   'A_DM',     '',                      true );
INSERT INTO CME VALUES ('Delete', '',                   'A_DM',     '',                      true );
INSERT INTO CME VALUES ('Rename', '',                   'A_OBJ',    '',                      true );
INSERT INTO CME VALUES ('Delete', '',                   'A_OBJ',    '',                      true );
INSERT INTO CME VALUES ('Rename', '',                   'A_AEA',    '',                      true );
INSERT INTO CME VALUES ('Delete', '',                   'A_AEA',    '',                      true );
INSERT INTO CME VALUES ('Rename', '',                   'A_ATE',    '',                      true );
INSERT INTO CME VALUES ('Delete', '',                   'A_ATE',    '',                      true );
INSERT INTO CME VALUES ('Rename', '',                   'A_SS',     '',                      true );
INSERT INTO CME VALUES ('Delete', '',                   'A_SS',     '',                      true );
INSERT INTO CME VALUES ('Rename', '',                   'A_AP',     '',                      true );
INSERT INTO CME VALUES ('Delete', '',                   'A_AP',     '',                      true );
INSERT INTO CME VALUES ('Delete', '',                   'S_SDT',    '',                      true );
INSERT INTO CME VALUES ('Rename', '',                   'S_SDT',    '',                      true );
INSERT INTO CME VALUES ('New',    'Member',             'S_SDT',    'S_MBR',                 false, '', '', false, '', false, false, '' ,'->S_MBR[R44]');
INSERT INTO CME VALUES ('Delete', '',                   'S_MBR',    '',                      true );
INSERT INTO CME VALUES ('Rename', '',                   'S_MBR',    '',                      true );
INSERT INTO CME VALUES ('',       'Move Up',            'S_MBR',    '',                      false, '' );
INSERT INTO CME VALUES ('',       'Move Down',          'S_MBR',    '',                      false, '' );
INSERT INTO CME VALUES ('Delete', '',                   'EP_PKG',   '',                      true );
INSERT INTO CME VALUES ('Rename', '',                   'EP_PKG',   '',                      true );
INSERT INTO CME VALUES ('Classes',  	'Imported Class', 	    'EP_PKG',    'O_IOBJ',          false);
INSERT INTO CME VALUES ('Classes',  	'Class',        	    'EP_PKG',    'O_OBJ',           false, '', '', false, '', false, false, '' ,'->PE_PE[R8000]->O_OBJ[R8001]');
INSERT INTO CME VALUES ('Components',   'Interface',  			'EP_PKG',    'C_I',   	        false, '', '', false, '', false, false, '' ,'->PE_PE[R8000]->C_I[R8001]');
INSERT INTO CME VALUES ('Components',   'Component Reference',  'EP_PKG',    'CL_IC',   	    false);
INSERT INTO CME VALUES ('Components',   'Component', 			'EP_PKG',    'C_C',             false, '', '', false, '', false, false, '' ,'->PE_PE[R8000]->C_C[R8001]');
INSERT INTO CME VALUES ('External',     'External Entity',      'EP_PKG',    'S_EE',            false, '', '', false, '', false, false, '' ,'->PE_PE[R8000]->S_EE[R8001]');
INSERT INTO CME VALUES ('Interaction',  'Class', 	              'EP_PKG',    'SQ_CP',         false, '', '', false, '', false, false, '' ,'->PE_PE[R8000]->SQ_P[R8001]->SQ_CP[R930]');
INSERT INTO CME VALUES ('Interaction',  'Package Participant',    'EP_PKG',    'SQ_PP',         false, '', '', false, '', false, false, '' ,'->PE_PE[R8000]->SQ_P[R8001]->SQ_PP[R930]');
INSERT INTO CME VALUES ('Interaction',  'External Entity',  	  'EP_PKG',    'SQ_EEP',        false, '', '', false, '', false, false, '' ,'->PE_PE[R8000]->SQ_P[R8001]->SQ_EEP[R930]');
INSERT INTO CME VALUES ('Interaction',  'Instance', 			  'EP_PKG',    'SQ_CIP',        false, '', '', false, '', false, false, '' ,'->PE_PE[R8000]->SQ_P[R8001]->SQ_CIP[R930]');
INSERT INTO CME VALUES ('Interaction',  'Component',              'EP_PKG',    'SQ_COP',        false, '', '', false, '', false, false, '' ,'->PE_PE[R8000]->SQ_P[R8001]->SQ_COP[R930]');
INSERT INTO CME VALUES ('Interaction',  'Actor', 	              'EP_PKG',    'SQ_AP',         false, '', '', false, '', false, false, '' ,'->PE_PE[R8000]->SQ_P[R8001]->SQ_AP[R930]');
INSERT INTO CME VALUES ('Activity',  'Object Node',  			  'EP_PKG',    'A_OBJ',         false, '', '', false, '', false, false, '' ,'->PE_PE[R8000]->A_N[R8001]->A_OBJ[R1105]');
INSERT INTO CME VALUES ('Activity',  'Send Signal Action',  	  'EP_PKG',    'A_SS',          false, '', '', false, '', false, false, '' ,'->PE_PE[R8000]->A_N[R8001]->A_ACT[R1105]->A_SS[R1107]');
INSERT INTO CME VALUES ('Activity',  'Action',					  'EP_PKG',    'A_GA',         false, '', '', false, '', false, false, '' ,'->PE_PE[R8000]->A_N[R8001]->A_ACT[R1105]->A_GA[R1107]');
INSERT INTO CME VALUES ('Activity',  'Accept Time Event Action',  'EP_PKG',    'A_ATE',         false, '', '', false, '', false, false, '' ,'->PE_PE[R8000]->A_N[R8001]->A_ACT[R1105]->A_AE[R1107]->A_ATE[R1112]');
INSERT INTO CME VALUES ('Activity',  'Accept Event Action',  	  'EP_PKG',    'A_AEA',         false, '', '', false, '', false, false, '' ,'->PE_PE[R8000]->A_N[R8001]->A_ACT[R1105]->A_AE[R1107]->A_AEA[R1112]');
INSERT INTO CME VALUES ('Types',  'Enumeration DataType',     'EP_PKG',    'S_EDT',         false, '', '', false, '', false, false, '' ,'->PE_PE[R8000]->S_DT[R8001]->S_EDT[R17]');
INSERT INTO CME VALUES ('Types',  'Structured DataType',      'EP_PKG',    'S_SDT',         false, '', '', false, '', false, false, '' ,'->PE_PE[R8000]->S_DT[R8001]->S_SDT[R17]');
INSERT INTO CME VALUES ('Types',  'Constant Specification',   'EP_PKG',    'CNST_CSP',      false, '', '', false, '', false, false, '' ,'->PE_PE[R8000]->CNST_CSP[R8001]');
INSERT INTO CME VALUES ('Types',  'User DataType',  		  'EP_PKG',    'S_UDT',         false, '', '', false, '', false, false, '' ,'->PE_PE[R8000]->S_DT[R8001]->S_UDT[R17]');
INSERT INTO CME VALUES ('Usecase',  'Usecase',  			  'EP_PKG',    'IA_UCP',         false, '', '', false, '', false, false, '' ,'->PE_PE[R8000]->SQ_P[R8001]->IA_UCP[R930]');
INSERT INTO CME VALUES ('New',    'Function',           'EP_PKG',    'S_SYNC',               false, '', '', false, '', false, false, '' ,'->PE_PE[R8000]->S_SYNC[R8001]');
INSERT INTO CME VALUES ('New','Package',                'EP_PKG',   'EP_PKG',                false, '', '', false, '', false, false, '' ,'->PE_PE[R8000]->EP_PKG[R8001]');
INSERT INTO CME VALUES ('',       'Publish References',  'O_OBJ',   '',                      false, '' );
INSERT INTO CME VALUES ('',       'Move Up',             'O_TPARM', '',                      false, '' );
INSERT INTO CME VALUES ('',       'Move Down',           'O_TPARM', '',                      false, '' );
INSERT INTO CME VALUES ('',       'Move Up',             'S_SPARM', '',                      false, '' );
INSERT INTO CME VALUES ('',       'Move Down',           'S_SPARM', '',                      false, '' );
INSERT INTO CME VALUES ('',       'Move Up',             'S_BPARM', '',                      false, '' );
INSERT INTO CME VALUES ('',       'Move Down',           'S_BPARM', '',                      false, '' );
INSERT INTO CME VALUES ('',       'Move Up',             'SM_EVTDI','',                      false, '' );
INSERT INTO CME VALUES ('',       'Move Down',           'SM_EVTDI','',                      false, '' );
INSERT INTO CME VALUES ('',       'Move Up',             'C_PP',    '',                      false, '' );
INSERT INTO CME VALUES ('',       'Move Down',           'C_PP',    '',                      false, '' );
INSERT INTO CME VALUES ('',       'Move Up',             'O_TFR',   '',                      false, '' );
INSERT INTO CME VALUES ('',       'Move Down',           'O_TFR',   '',                      false, '' );
INSERT INTO CME VALUES ('',       'Move Up',             'C_AS',    '',                      false, '' );
INSERT INTO CME VALUES ('',       'Move Down',           'C_AS',    '',                      false, '' );
INSERT INTO CME VALUES ('',       'Move Up',             'C_IO',    '',                      false, '' );
INSERT INTO CME VALUES ('',       'Move Down',           'C_IO',    '',                      false, '' );
INSERT INTO CME VALUES ('',       'Move Up',             'S_ENUM',  '',                      false, '' );
INSERT INTO CME VALUES ('',       'Move Down',           'S_ENUM',  '',                      false, '' );
INSERT INTO CME VALUES ('',       'Disconnect',          'C_P',     '',                      false, '' );
INSERT INTO CME VALUES ('',       'Disconnect',          'C_R',     '',                      false, '' );
INSERT INTO CME VALUES ('',       'Disconnect',          'CL_IP',   '',                      false, '' );
INSERT INTO CME VALUES ('',       'Disconnect',          'CL_IR',   '',                      false, '' );
INSERT INTO CME VALUES ('Set',       'Return Type',      'C_IO',    'S_DT',                  false, '', '*', false, '', true );
INSERT INTO CME VALUES ('Set',       'Type',             'C_PP',    'S_DT',                  false, '', '*', false, '', true );
INSERT INTO CME VALUES ('Set',       'Type',             'S_BPARM', 'S_DT',                  false, '', '*', false, '', true );
INSERT INTO CME VALUES ('Set',       'Return Type',      'S_BRG',   'S_DT',                  false, '', '*', false, '', true );
INSERT INTO CME VALUES ('Set',       'Return Type',      'S_SYNC',  'S_DT',                  false, '', '*', false, '', true );
INSERT INTO CME VALUES ('Set',       'Type',             'S_SPARM', 'S_DT',                  false, '', '*', false, '', true );
INSERT INTO CME VALUES ('Set',       'Type',             'S_MBR',   'S_DT',                  false, '', '*', false, '', true );
INSERT INTO CME VALUES ('Set',       'Type',             'SM_EVTDI','S_DT',                  false, '', '*', false, '', true );
INSERT INTO CME VALUES ('Set',       'Type',             'O_TPARM', 'S_DT',                  false, '', '*', false, '', true );
INSERT INTO CME VALUES ('Set',       'Return Type',      'O_TFR',   'S_DT',                  false, '', '*', false, '', true );
INSERT INTO CME VALUES ('Set',       'Type',             'O_ATTR',  'S_DT',                  false, '', '*', false, '', true );
INSERT INTO CME VALUES ('Set',       'Type',             'S_UDT',   'S_DT',                  false, '', '*', false, '', true );
INSERT INTO CME VALUES ('Set',       'Type',             'CNST_LSC','S_DT',                  false, '', '*', false, '', true );
INSERT INTO CME VALUES ('Generic Package', 'Assign Class', 'O_IOBJ', 'O_OBJ',                 false, 'Select class this imported class represents', '1', false, '', true, false, 'class' );
INSERT INTO CME VALUES ('Generic Package', 'Assign Component', 'CL_IC', 'C_C',                false, 'Choose the component to reference', '*', false, '', true, false, 'component'); 
INSERT INTO CME VALUES ('',          'Make Public',      'O_OBJ',   '',                      false, '' );
INSERT INTO CME VALUES ('',          'Make Protected',   'O_OBJ',   '',                      false, '' );
INSERT INTO CME VALUES ('',          'Make Private',     'O_OBJ',   '',                      false, '' );
INSERT INTO CME VALUES ('',          'Make Public',      'C_C',   '',                        false, '' );
INSERT INTO CME VALUES ('',          'Make Protected',   'C_C',   '',                        false, '' );
INSERT INTO CME VALUES ('',          'Make Private',     'C_C',   '',                        false, '' );
INSERT INTO CME VALUES ('',          'Make Public',      'S_UDT',   '',                      false, '' );
INSERT INTO CME VALUES ('',          'Make Protected',   'S_UDT',   '',                      false, '' );
INSERT INTO CME VALUES ('',          'Make Private',     'S_UDT',   '',                      false, '' );
INSERT INTO CME VALUES ('',          'Make Public',      'EP_PKG',  '',                      false, '' );
INSERT INTO CME VALUES ('',          'Make Protected',   'EP_PKG',   '',                      false, '' );
INSERT INTO CME VALUES ('',          'Make Private',     'EP_PKG',  '',                      false, '' );
INSERT INTO CME VALUES ('',          'Make Public',      'S_EDT',   '',                      false, '' );
INSERT INTO CME VALUES ('',          'Make Protected',   'S_EDT',   '',                      false, '' );
INSERT INTO CME VALUES ('',          'Make Private',     'S_EDT',   '',                      false, '' );
INSERT INTO CME VALUES ('',          'Make Public',      'S_SDT',   '',                      false, '' );
INSERT INTO CME VALUES ('',          'Make Protected',   'S_SDT',   '',                      false, '' );
INSERT INTO CME VALUES ('',          'Make Private',     'S_SDT',   '',                      false, '' );
INSERT INTO CME VALUES ('',          'Make Public',      'CNST_CSP',   '',                   false, '' );
INSERT INTO CME VALUES ('',          'Make Protected',   'CNST_CSP',   '',                   false, '' );
INSERT INTO CME VALUES ('',          'Make Private',     'CNST_CSP',   '',                   false, '' );

-- Generic package interaction formalization CME definitions
INSERT INTO CME VALUES ('Generic Package',      'Formalize',    'SQ_COP','',  false, 'Choose the component that this instance should represent' , '1', false, '', true, true, 'component');
INSERT INTO CME VALUES ('Generic Package',      'Formalize',    'SQ_CIP','',  false, 'Choose the class that this instance should represent' , '1', false, '', true, true, 'class');
INSERT INTO CME VALUES ('Generic Package',      'Formalize',    'SQ_CP', '',  false, 'Choose the class to import'  , '1', false, '', true, true, 'class');
INSERT INTO CME VALUES ('Generic Package',        'Formalize',    'SQ_EEP','',                 false, 'Choose the External Entity that this instance should represent' , '1', false, '', true, true, 'external entity');
INSERT INTO CME VALUES ('',                    'Formalize',    'SQ_PP', '',                 false, 'Choose the Package that this instance should represent' , '1', false, '', true, true, 'package');
INSERT INTO CME VALUES ('Communication Package Function', 'Formalize',             'MSG_SM',     '', false, 'Choose the message to send', '2', true);
INSERT INTO CME VALUES ('Package Function',       'Formalize',    'MSG_SM','',                 false, 'Choose the message to send' );
-- Common interaction formalization CME definitions

INSERT INTO CME VALUES ('Bridge Operation',   'Formalize',    'MSG_SM','',                 false, 'Choose the message to send' );
INSERT INTO CME VALUES ('Instance Operation', 'Formalize',    'MSG_SM','',                 false, 'Choose the message to send' );
INSERT INTO CME VALUES ('Class Operation',    'Formalize',    'MSG_SM','',                 false, 'Choose the message to send' );
INSERT INTO CME VALUES ('Interface Operation', 'Formalize',    'MSG_SM','',                 false, 'Choose the message to send' );
INSERT INTO CME VALUES ('Class Event',        'Formalize',    'MSG_AM','',                 false, 'Choose the message to send' );
INSERT INTO CME VALUES ('Instance Class Event', 'Formalize',  'MSG_AM','',                 false, 'Choose the message to send' );
INSERT INTO CME VALUES ('Instance Event', 'Formalize',    'MSG_AM','',                 false, 'Choose the message to send' );
INSERT INTO CME VALUES ('Signal',         'Formalize',    'MSG_AM','',                 false, 'Choose the message to send' );
INSERT INTO CME VALUES ('Instance',         'Unformalize',    'SQ_CIP','',                 false );
INSERT INTO CME VALUES ('Class',            'Unformalize',    'SQ_CP', '',                 false );
INSERT INTO CME VALUES ('External Entity',  'Unformalize',    'SQ_EEP','',                 false );
INSERT INTO CME VALUES ('Function Package', 'Unformalize',    'SQ_FPP','',                 false );
INSERT INTO CME VALUES ('Package Participant', 'Unformalize',    'SQ_PP','',                 false );
INSERT INTO CME VALUES ('Message',          'Unformalize',    'MSG_SM','',                 false );
INSERT INTO CME VALUES ('Message',          'Unformalize',    'MSG_AM','',                 false );
INSERT INTO CME VALUES ('',       'Mark Instance Destroyed',  'SQ_LS', '',                 false );
INSERT INTO CME VALUES ('',     'Mark Instance not Destroyed','SQ_LS', '',                 false );
INSERT INTO CME VALUES ('Link', 'Formalize',            'COMM_LNK', '',                      false, 'Choose the association to formalize with' );
INSERT INTO CME VALUES ('', 'Unformalize',              'COMM_LNK', '',                      false, '' );
INSERT INTO CME VALUES ('', 'Toggle Start Visibility',  'COMM_LNK', '',                      false, '' );
INSERT INTO CME VALUES ('', 'Toggle End Visibility',    'COMM_LNK', '',                      false, '' );
INSERT INTO CME VALUES ('Communication Class Operation',  'Formalize',     'MSG_SM',     '', false, 'Choose the message to send', '2', true);
INSERT INTO CME VALUES ('Communication Instance Operation','Formalize',    'MSG_SM',     '', false, 'Choose the message to send', '2', true);
INSERT INTO CME VALUES ('Communication Bridge Operation', 'Formalize',     'MSG_SM',     '', false, 'Choose the message to send', '2', true);
INSERT INTO CME VALUES ('Communication Interface Operation', 'Formalize',  'MSG_SM',     '', false, 'Choose the message to send', '2', true);
INSERT INTO CME VALUES ('Communication Class Event', 'Formalize',          'MSG_AM',     '', false, 'Choose the message to send', '2', true);
INSERT INTO CME VALUES ('Communication Instance Event', 'Formalize',       'MSG_AM',     '', false, 'Choose the message to send', '2', true);
INSERT INTO CME VALUES ('Communication Signal',     'Formalize',       'MSG_AM',     '', false, 'Choose the message to send', '2', true);
INSERT INTO CME VALUES ('No Target', 'Formalize',       'MSG_SM',   '',                      false, '', '1', false, ' (No Target Selected)');
INSERT INTO CME VALUES ('No Target', 'Formalize',       'MSG_AM',   '',                      false, '', '1', false, ' (No Target Selected)');
INSERT INTO CME VALUES ('New', 'Argument',                    'MSG_SM','MSG_A',            false , '', '', false, '', false, false, '' ,'->MSG_M[R1018]->MSG_A[R1000]');
INSERT INTO CME VALUES ('New', 'Argument',                    'MSG_AM','MSG_A',            false , '', '', false, '', false, false, '' ,'->MSG_M[R1018]->MSG_A[R1000]');
INSERT INTO CME VALUES ('New', 'Argument',                    'MSG_R', 'MSG_A',            false , '', '', false, '', false, false, '' ,'->MSG_M[R1018]->MSG_A[R1000]');
INSERT INTO CME VALUES ('New', 'Attribute',                   'SQ_CIP','SQ_AV',            false , '', '', false, '', false, false, '' ,'->SQ_AV[R936]');
INSERT INTO CME VALUES ('New', 'Attribute',                   'SQ_CP', 'SQ_CPA',           false , '', '', false, '', false, false, '' ,'->SQ_CPA[R935]');
INSERT INTO CME VALUES ('',                                   'Unformalize',   'SQ_COP', '', false );

-- Specialized package formalization CME definitions
INSERT INTO CME VALUES ('Specialized Package Instance',  'Formalize',    'SQ_CIP','',  false, 'Choose the class that this instance should represent' );
INSERT INTO CME VALUES ('Specialized Package Class',  'Formalize',    'SQ_CP', '',  false, 'Choose the class to import' );
INSERT INTO CME VALUES ('Specialized Package External Entity',    'Formalize',    'SQ_EEP','',                 false, 'Choose the External Entity that this instance should represent' );
INSERT INTO CME VALUES ('',   'Formalize',    'SQ_FPP','',                 false, 'Choose the Function Package that this instance should represent' );
INSERT INTO CME VALUES ('Specialized Package',                'Formalize',     'SQ_COP', '', false, 'Choose the Component that this symbol shall represent' );
INSERT INTO CME VALUES ('Communication Function', 'Formalize',             'MSG_SM',     '', false, 'Choose the message to send', '2', true);
INSERT INTO CME VALUES ('Function',       'Formalize',    'MSG_SM','',                 false, 'Choose the message to send' );
INSERT INTO CME VALUES ('Delete', '',                         'SPR_RO', '',                 true );
INSERT INTO CME VALUES ('Delete', '',                         'SPR_RS', '',                 true );
INSERT INTO CME VALUES ('Delete', '',                         'SPR_PO', '',                 true );
INSERT INTO CME VALUES ('Delete', '',                         'SPR_PS', '',                 true );
INSERT INTO CME VALUES ('', 'Set To Provider',                         'C_AS', '',                 false );
INSERT INTO CME VALUES ('', 'Set From Provider',                         'C_AS', '',                 false );
INSERT INTO CME VALUES ('', 'Set To Provider',                         'C_IO', '',                 false );
INSERT INTO CME VALUES ('', 'Set From Provider',                         'C_IO', '',                 false );
--
INSERT INTO MEF VALUES ('New',	  'Package',                  'C_C',   'new', 'package' );
INSERT INTO MEF VALUES ('New',    'Component',         		  'C_C',   'new', 'component' );
INSERT INTO MEF VALUES ('New',    'Imported Component',       'C_C',   'new', 'imported component' );
INSERT INTO MEF VALUES ('',    'Disconnect',  'C_P',    'can', 'dissatisfy' );
INSERT INTO MEF VALUES ('',    'Disconnect',  'C_R',    'can', 'dissatisfy' );
INSERT INTO MEF VALUES ('',    'Disconnect',  'CL_IP',    'can', 'dissatisfy' );
INSERT INTO MEF VALUES ('',    'Disconnect',  'CL_IR',    'can', 'dissatisfy' );
INSERT INTO MEF VALUES ('Set',    'Type',  'S_UDT',    'can', 'SetType' );
INSERT INTO MEF VALUES ('Set',    'Type',  'O_ATTR',    'can', 'SetType' );
INSERT INTO MEF VALUES ('',       'Add to Identifier',  'O_ATTR',    'id', 'not all' );
INSERT INTO MEF VALUES ('',       'Remove from Identifier',  'O_ATTR', 'id', 'some' );
INSERT INTO MEF VALUES ('',       'Set as Derived Attribute', 'O_ATTR', 'subtype', 'O_NBATTR');
INSERT INTO MEF VALUES ('',       'Set as Base Attribute', 'O_ATTR', 'subtype', 'O_DBATTR');
INSERT INTO MEF VALUES ('',       'Move Up',       'O_ATTR',    'can', 'move up' );
INSERT INTO MEF VALUES ('',       'Move Down',     'O_ATTR',    'can', 'move down' );
INSERT INTO MEF VALUES ('',       'Combine With',  'O_ATTR',    'can', 'combine' );
INSERT INTO MEF VALUES ('',       'Split',         'O_ATTR',    'can', 'split' );
INSERT INTO MEF VALUES ('Specialized Package',   'Assign Class',  'O_IOBJ', 'unassigned', 'spec pkg' );

INSERT INTO MEF VALUES ('Generic Package',       'Assign Class',  'O_IOBJ', 'unassigned', 'generic pkg' );

INSERT INTO MEF VALUES ('Binary',     'Formalize',          'R_REL', 'type', 'unform simp' );
INSERT INTO MEF VALUES ('Linked',     'Formalize',          'R_REL', 'type', 'unform assoc' );
INSERT INTO MEF VALUES ('Linked',     'Formalize',          'R_ASSR','type', 'unform assoc' );
INSERT INTO MEF VALUES ('Inheritance','Formalize',          'R_REL', 'type', 'unform subsup' );
INSERT INTO MEF VALUES ('Inheritance','Formalize',          'R_SUB', 'type', 'unform subsup' );
INSERT INTO MEF VALUES ('',       'Unformalize',          'R_REL', 'formalized', 'true' );
INSERT INTO MEF VALUES ('',       'Unformalize',          'R_ASSR','formalized', 'true' );
INSERT INTO MEF VALUES ('',       'Unformalize',          'R_SUB', 'formalized', 'true' );
INSERT INTO MEF VALUES ('Specialized Package',   'Assign Event',  'SM_TXN',    'event', 'exists spec pkg' );
INSERT INTO MEF VALUES ('Generic Package',       'Assign Event',  'SM_TXN',    'event', 'exists generic pkg' );
INSERT INTO MEF VALUES ('Specialized Package',   'Assign Signal', 'SM_TXN',    'signal', 'exists spec pkg' );
INSERT INTO MEF VALUES ('Generic Package',       'Assign Signal', 'SM_TXN',    'signal', 'exists generic pkg' );
INSERT INTO MEF VALUES ('',       'Remove Event',  'SM_TXN',    'event', 'assigned' );
INSERT INTO MEF VALUES ('',       'Remove Signal',  'SM_TXN',    'signal', 'assigned' );
INSERT INTO MEF VALUES ('Specialized Package',       'Assign Event',  'SM_CRTXN',    'event', 'exists spec pkg' );
INSERT INTO MEF VALUES ('Generic Package',           'Assign Event',  'SM_CRTXN',    'event', 'exists generic pkg' );
INSERT INTO MEF VALUES ('',       'Remove Event',  'SM_CRTXN',    'event', 'assigned' );
INSERT INTO MEF VALUES ('Specialized Package',   'Ignore in State',  'SM_EVT',    'can', 'ignore spec pkg' );
INSERT INTO MEF VALUES ('Generic Package',       'Ignore in State',  'SM_EVT',    'can', 'ignore generic pkg' );
INSERT INTO MEF VALUES ('Specialized Package',       'Cant Happen in State',  'SM_EVT',    'can', 'ch spec pkg' );
INSERT INTO MEF VALUES ('Generic Package',       'Cant Happen in State',  'SM_EVT',    'can', 'ch generic pkg' );
INSERT INTO MEF VALUES ('Specialized Package',       'Ignore Event',  'SM_STATE',    'can', 'ignore spec pkg' );
INSERT INTO MEF VALUES ('Generic Package',       'Ignore Event',  'SM_STATE',    'can', 'ignore generic pkg' );
INSERT INTO MEF VALUES ('Specialized Package',       'Cant Happen Event',  'SM_STATE',    'can', 'ch spec pkg' );
INSERT INTO MEF VALUES ('Generic Package',       'Cant Happen Event',  'SM_STATE',    'can', 'ch generic pkg' );
INSERT INTO MEF VALUES ('New',       'Instance State Machine',  'O_OBJ',    'can', 'instanceStateChart' );
INSERT INTO MEF VALUES ('New',       'Class State Machine',  'O_OBJ',    'can', 'classStateChart' );
INSERT INTO MEF VALUES ('New',       'Argument',  'MSG_SM',    'can', 'addArg' );
INSERT INTO MEF VALUES ('New',       'Argument',  'MSG_AM',    'can', 'addArg' );
INSERT INTO MEF VALUES ('New',       'Attribute',  'SQ_CIP',    'can', 'addAttr' );
INSERT INTO MEF VALUES ('New',       'Attribute',  'SQ_CP',    'can', 'addAttr' );
INSERT INTO MEF VALUES ('Component',    'Formalize',  'C_C',    'can', 'formalize' );
INSERT INTO MEF VALUES ('Specialized Package Provided Interface',    'Formalize',  'C_P',    'can', 'formalize spec pkg' );
INSERT INTO MEF VALUES ('Generic Package',        'Formalize',  'C_P',    'can', 'formalize generic pkg' );
INSERT INTO MEF VALUES ('Provided Interface',    'Unformalize',  'C_P',    'can', 'unformalize' );
INSERT INTO MEF VALUES ('Specialized Package Required Interface', 'Formalize',  'C_R',    'can', 'formalize spec pkg' );
INSERT INTO MEF VALUES ('Generic Package',     'Formalize',  'C_R',    'can', 'formalize generic pkg' );
INSERT INTO MEF VALUES ('Required Interface',    'Unformalize',  'C_R',    'can', 'unformalize' );
INSERT INTO MEF VALUES ('Specialized Package',    'Formalize',  'C_DG',    'can', 'formalize spec pkg' );
INSERT INTO MEF VALUES ('Generic Package',        'Formalize',  'C_DG',    'can', 'formalize generic pkg' );
INSERT INTO MEF VALUES ('',    'Unformalize',  'C_DG',    'can', 'unformalize' );
INSERT INTO MEF VALUES ('Specialized Package',    'Assign Component',  'CL_IC',    'can', 'assign spec pkg' );
INSERT INTO MEF VALUES ('Generic Package',        'Assign Component',  'CL_IC',    'can', 'assign generic pkg' );
INSERT INTO MEF VALUES ('',    'Unassign',  'CL_IC',    'can', 'unassign' );
INSERT INTO MEF VALUES ('',       'Move Up',       'S_MBR',    'can', 'move up' );
INSERT INTO MEF VALUES ('',       'Move Down',     'S_MBR',    'can', 'move down' );
INSERT INTO MEF VALUES ('',       'Publish References',  'O_OBJ',    'can', 'publishRefs' );
INSERT INTO MEF VALUES ('',       'Move Up',       'O_TPARM',    'can', 'move up' );
INSERT INTO MEF VALUES ('',       'Move Down',     'O_TPARM',    'can', 'move down' );
INSERT INTO MEF VALUES ('',       'Move Up',       'S_SPARM',    'can', 'move up' );
INSERT INTO MEF VALUES ('',       'Move Down',     'S_SPARM',    'can', 'move down' );
INSERT INTO MEF VALUES ('',       'Move Up',       'S_BPARM',    'can', 'move up' );
INSERT INTO MEF VALUES ('',       'Move Down',     'S_BPARM',    'can', 'move down' );
INSERT INTO MEF VALUES ('',       'Move Up',       'SM_EVTDI',    'can', 'move up' );
INSERT INTO MEF VALUES ('',       'Move Down',     'SM_EVTDI',    'can', 'move down' );
INSERT INTO MEF VALUES ('',       'Move Up',       'C_PP',    'can', 'move up' );
INSERT INTO MEF VALUES ('',       'Move Down',     'C_PP',    'can', 'move down' );
INSERT INTO MEF VALUES ('',       'Move Up',       'O_TFR',    'can', 'move up' );
INSERT INTO MEF VALUES ('',       'Move Down',     'O_TFR',    'can', 'move down' );
INSERT INTO MEF VALUES ('',       'Move Up',       'C_AS',    'can', 'move up' );
INSERT INTO MEF VALUES ('',       'Move Down',     'C_AS',    'can', 'move down' );
INSERT INTO MEF VALUES ('',       'Move Up',       'C_IO',    'can', 'move up' );
INSERT INTO MEF VALUES ('',       'Move Down',     'C_IO',    'can', 'move down' );
INSERT INTO MEF VALUES ('',       'Move Up',       'S_ENUM',    'can', 'move up' );
INSERT INTO MEF VALUES ('',       'Move Down',     'S_ENUM',    'can', 'move down' );
INSERT INTO MEF VALUES ('',       'Make Public',   'O_OBJ',     'can', 'make public' );
INSERT INTO MEF VALUES ('',       'Make Protected','O_OBJ',     'can', 'make protected' );
INSERT INTO MEF VALUES ('',       'Make Private',  'O_OBJ',     'can', 'make private' );
INSERT INTO MEF VALUES ('',       'Make Public',   'C_C',       'can', 'make public' );
INSERT INTO MEF VALUES ('',       'Make Protected','C_C',       'can', 'make protected' );
INSERT INTO MEF VALUES ('',       'Make Private',  'C_C',       'can', 'make private' );
INSERT INTO MEF VALUES ('',       'Make Public',   'S_UDT',     'can', 'make public' );
INSERT INTO MEF VALUES ('',       'Make Protected','S_UDT',     'can', 'make protected' );
INSERT INTO MEF VALUES ('',       'Make Private',  'S_UDT',     'can', 'make private' );
INSERT INTO MEF VALUES ('',       'Make Public',   'EP_PKG',    'can', 'make public' );
INSERT INTO MEF VALUES ('',       'Make Protected','EP_PKG',    'can', 'make protected' );
INSERT INTO MEF VALUES ('',       'Make Private',  'EP_PKG',    'can', 'make private' );
INSERT INTO MEF VALUES ('',       'Make Public',   'S_EDT',     'can', 'make public' );
INSERT INTO MEF VALUES ('',       'Make Protected','S_EDT',     'can', 'make protected' );
INSERT INTO MEF VALUES ('',       'Make Private',  'S_EDT',     'can', 'make private' );
INSERT INTO MEF VALUES ('',       'Make Public',   'S_SDT',     'can', 'make public' );
INSERT INTO MEF VALUES ('',       'Make Protected','S_SDT',     'can', 'make protected' );
INSERT INTO MEF VALUES ('',       'Make Private',  'S_SDT',     'can', 'make private' );
INSERT INTO MEF VALUES ('',       'Make Public',   'CNST_CSP',     'can', 'make public' );
INSERT INTO MEF VALUES ('',       'Make Protected','CNST_CSP',     'can', 'make protected' );
INSERT INTO MEF VALUES ('',       'Make Private',  'CNST_CSP',     'can', 'make private' );

-- Interaction element filtering

-- Formalize interaction participants
INSERT INTO MEF VALUES ('Specialized Package Instance',  'Formalize',  'SQ_CIP',    'can', 'formClass spec pkg' );
INSERT INTO MEF VALUES ('Generic Package',      'Formalize',  'SQ_CIP',    'can', 'formClass generic pkg' );
INSERT INTO MEF VALUES ('Specialized Package Class',  'Formalize',  'SQ_CP',    'can', 'formClass spec pkg' );
INSERT INTO MEF VALUES ('Generic Package',      'Formalize',  'SQ_CP',    'can', 'formClass generic pkg' );
INSERT INTO MEF VALUES ('Specialized Package External Entity',     'Formalize',  'SQ_EEP',    'can', 'formEE spec pkg' );
INSERT INTO MEF VALUES ('Generic Package',         'Formalize',  'SQ_EEP',    'can', 'formEE generic pkg' );
INSERT INTO MEF VALUES ('Specialized Package Function Package',    'Formalize',  'SQ_FPP',    'can', 'formFP spec pkg' );
INSERT INTO MEF VALUES ('',    'Formalize',  'SQ_PP',    'can', 'formPkg' );
INSERT INTO MEF VALUES ('Specialized Package',    'Formalize',  'SQ_COP',    'can', 'formComp spec pkg' );
INSERT INTO MEF VALUES ('Generic Package',    'Formalize',  'SQ_COP',    'can', 'formComp generic pkg' );
-- Formalize messages
-- Formalize non-communication
INSERT INTO MEF VALUES ('Link',    'Formalize',  'COMM_LNK',    'can', 'formalize' );
INSERT INTO MEF VALUES ('Class Operation',    'Formalize',  'MSG_SM',    'can', 'formClassOp' );
INSERT INTO MEF VALUES ('Instance Operation',    'Formalize',  'MSG_SM',    'can', 'formInstOp' );
INSERT INTO MEF VALUES ('Bridge Operation',    'Formalize',  'MSG_SM',    'can', 'formBrg' );
INSERT INTO MEF VALUES ('Function',    'Formalize',  'MSG_SM',    'can', 'formFunc' );
INSERT INTO MEF VALUES ('Package Function',    'Formalize',  'MSG_SM',    'can', 'formPkgFunc' );
INSERT INTO MEF VALUES ('Interface Operation',    'Formalize',  'MSG_SM',    'can', 'formIOp' );
INSERT INTO MEF VALUES ('Instance Event',    'Formalize',  'MSG_AM',    'can', 'formInstEvent' );
INSERT INTO MEF VALUES ('Signal',    'Formalize',  'MSG_AM',    'can', 'formSig' );
INSERT INTO MEF VALUES ('Class Event',    'Formalize',  'MSG_AM',    'can', 'formClassEvent' );
INSERT INTO MEF VALUES ('Instance Class Event',    'Formalize',  'MSG_AM',    'can', 'formInstClassEvent' );
-- Formalize communication
INSERT INTO MEF VALUES ('Communication Class Operation',    'Formalize',  'MSG_SM',    'can', 'formCommClassOp' );
INSERT INTO MEF VALUES ('Communication Instance Operation',    'Formalize',  'MSG_SM',    'can', 'formCommInstOp' );
INSERT INTO MEF VALUES ('Communication Bridge Operation',    'Formalize',  'MSG_SM',    'can', 'formCommBrg' );
INSERT INTO MEF VALUES ('Communication Function',    'Formalize',  'MSG_SM',    'can', 'formCommFunc' );
INSERT INTO MEF VALUES ('Communication Package Function',    'Formalize',  'MSG_SM',    'can', 'formCommPackageFunc' );
INSERT INTO MEF VALUES ('Communication Interface Operation',    'Formalize',  'MSG_SM',    'can', 'formCommMsgIOp' );
INSERT INTO MEF VALUES ('Communication Instance Event',    'Formalize',  'MSG_AM',    'can', 'formCommInstEvent' );
INSERT INTO MEF VALUES ('Communication Signal',    'Formalize',  'MSG_AM',    'can', 'formCommMsgSig' );
INSERT INTO MEF VALUES ('Communication Class Event',    'Formalize',  'MSG_AM',    'can', 'formCommClassEvent' );
INSERT INTO MEF VALUES ('No Target',    'Formalize',  'MSG_SM',    'show', 'noTargetMessage' );
INSERT INTO MEF VALUES ('No Target',    'Formalize',  'MSG_AM',    'show', 'noTargetMessage' );
-- Unformalize
INSERT INTO MEF VALUES ('Instance', 'Unformalize',  'SQ_CIP',    'can', 'unform' );
INSERT INTO MEF VALUES ('Class',               'Unformalize',  'SQ_CP',    'can', 'unform' );
INSERT INTO MEF VALUES ('External Entity',     'Unformalize',  'SQ_EEP',    'can', 'unform' );
INSERT INTO MEF VALUES ('Function Package',    'Unformalize',  'SQ_FPP',    'can', 'unform' );
INSERT INTO MEF VALUES ('Package Participant',    'Unformalize',  'SQ_PP',    'can', 'unform' );
INSERT INTO MEF VALUES ('Message',             'Unformalize',  'MSG_SM',    'can', 'unform' );
INSERT INTO MEF VALUES ('Message',             'Unformalize',  'MSG_AM',    'can', 'unform' );
INSERT INTO MEF VALUES ('',    'Unformalize',  'COMM_LNK',    'can', 'unformalize' );
INSERT INTO MEF VALUES ('',       'Unformalize',  'SQ_COP',    'can', 'unform' );
-- Other
INSERT INTO MEF VALUES ('',    'Mark Instance Destroyed',  'SQ_LS',    'can', 'destroy' );
INSERT INTO MEF VALUES ('',    'Mark Instance not Destroyed',  'SQ_LS',    'can', 'undestroy' );
INSERT INTO MEF VALUES ('',    'Set To Provider',  'C_AS',    'can', 'setToProvider' );
INSERT INTO MEF VALUES ('',    'Set From Provider',  'C_AS',    'can', 'setFromProvider' );
INSERT INTO MEF VALUES ('',    'Set To Provider',  'C_IO',    'can', 'setToProvider' );
INSERT INTO MEF VALUES ('',    'Set From Provider',  'C_IO',    'can', 'setFromProvider' );
