INSERT INTO UnsupportedElement VALUES ('A_AE');  -- 'Accept Event'
INSERT INTO UnsupportedElement VALUES ('A_AEA');  -- 'Accept Event Action'
INSERT INTO UnsupportedElement VALUES ('A_AF');  -- 'Activity Final Node'
INSERT INTO UnsupportedElement VALUES ('A_AP');  -- 'Activity Partition'
INSERT INTO UnsupportedElement VALUES ('A_ATE');  -- 'Accept Time Event Action'
INSERT INTO UnsupportedElement VALUES ('A_CTL');  -- 'Control Node'
INSERT INTO UnsupportedElement VALUES ('A_DM');  -- 'Decision Merge Node'
INSERT INTO UnsupportedElement VALUES ('A_E');  -- 'Activity Edge'
INSERT INTO UnsupportedElement VALUES ('A_FF');  -- 'Flow Final Node'
INSERT INTO UnsupportedElement VALUES ('A_FJ');  -- 'Fork Join Node'
INSERT INTO UnsupportedElement VALUES ('A_GA');  -- 'Activity Diagram Action'
INSERT INTO UnsupportedElement VALUES ('A_INI');  -- 'Initial Node'
INSERT INTO UnsupportedElement VALUES ('A_N');  -- 'Activity Node'
INSERT INTO UnsupportedElement VALUES ('A_OBJ');  -- 'Object Node'
INSERT INTO UnsupportedElement VALUES ('A_SS');  -- 'Send Signal'
INSERT INTO UnsupportedElement VALUES ('COMM_LNK');  -- 'Communication Link'
INSERT INTO UnsupportedElement VALUES ('C_DG');  -- 'Delegation'
INSERT INTO UnsupportedElement VALUES ('C_RID');  -- 'Interface Reference In Delegation'
INSERT INTO UnsupportedElement VALUES ('IA_UCP');  -- 'Use Case Participant'
INSERT INTO UnsupportedElement VALUES ('MSG_A');  -- 'Message Argument'
INSERT INTO UnsupportedElement VALUES ('MSG_AM');  -- 'Asynchronous Message'
INSERT INTO UnsupportedElement VALUES ('MSG_B');  -- 'Bridge Message'
INSERT INTO UnsupportedElement VALUES ('MSG_BA');  -- 'Bridge Argument'
INSERT INTO UnsupportedElement VALUES ('MSG_E');  -- 'Event Message'
INSERT INTO UnsupportedElement VALUES ('MSG_EA');  -- 'Event Argument'
INSERT INTO UnsupportedElement VALUES ('MSG_EPA');  -- 'Executable Property Argument'
INSERT INTO UnsupportedElement VALUES ('MSG_F');  -- 'Function Message'
INSERT INTO UnsupportedElement VALUES ('MSG_FA');  -- 'Function Argument'
INSERT INTO UnsupportedElement VALUES ('MSG_IA');  -- 'Informal Argument'
INSERT INTO UnsupportedElement VALUES ('MSG_IAM');  -- 'Informal Asynchronous Message'
INSERT INTO UnsupportedElement VALUES ('MSG_IOP');  -- 'Interface Operation Message'
INSERT INTO UnsupportedElement VALUES ('MSG_ISM');  -- 'Informal Synchronous Message'
INSERT INTO UnsupportedElement VALUES ('MSG_M');  -- 'Message'
INSERT INTO UnsupportedElement VALUES ('MSG_O');  -- 'Operation Message'
INSERT INTO UnsupportedElement VALUES ('MSG_OA');  -- 'Operation Argument'
INSERT INTO UnsupportedElement VALUES ('MSG_R');  -- 'Return Message'
INSERT INTO UnsupportedElement VALUES ('MSG_SIG');  -- 'Signal Message'
INSERT INTO UnsupportedElement VALUES ('MSG_SM');  -- 'Synchronous Message'
INSERT INTO UnsupportedElement VALUES ('O_DEF');  -- 'Deferral'
INSERT INTO UnsupportedElement VALUES ('R_COMP');  -- 'Derived Association'
INSERT INTO UnsupportedElement VALUES ('R_CONE');  -- 'Class As Derived One Side'
INSERT INTO UnsupportedElement VALUES ('R_COTH');  -- 'Class As Derived Other Side'
INSERT INTO UnsupportedElement VALUES ('SEN_ALE');  -- 'Action Language Engine'
INSERT INTO UnsupportedElement VALUES ('SEN_DCE');  -- 'Declarations Engine'
INSERT INTO UnsupportedElement VALUES ('SEN_DE');  -- 'Description Engine'
INSERT INTO UnsupportedElement VALUES ('SEN_E');  -- 'Search Engine'
INSERT INTO UnsupportedElement VALUES ('SEN_RE');  -- 'References Engine'
INSERT INTO UnsupportedElement VALUES ('SM_MEAH');  -- 'Mealy Action Home'
INSERT INTO UnsupportedElement VALUES ('SM_MEALY');  -- 'Mealy State Machine'
INSERT INTO UnsupportedElement VALUES ('SM_SDI');  -- 'Supplemental Data Items'
INSERT INTO UnsupportedElement VALUES ('SM_SGEVT');  -- 'Signal Event'
INSERT INTO UnsupportedElement VALUES ('SM_SUPDT');  -- 'Event Supplemental Data'
INSERT INTO UnsupportedElement VALUES ('SP_ALS');  -- 'Action Language Searchable'
INSERT INTO UnsupportedElement VALUES ('SP_DS');  -- 'Description Searchable'
INSERT INTO UnsupportedElement VALUES ('SP_NS');  -- 'Named Searchable'
INSERT INTO UnsupportedElement VALUES ('SP_SE');  -- 'Searchable Element'
INSERT INTO UnsupportedElement VALUES ('SP_SP');  -- 'Search Participant'
INSERT INTO UnsupportedElement VALUES ('SQU_A');  -- 'Action Language Query'
INSERT INTO UnsupportedElement VALUES ('SQU_D');  -- 'Declaration Query'
INSERT INTO UnsupportedElement VALUES ('SQU_DE');  -- 'Description Query'
INSERT INTO UnsupportedElement VALUES ('SQU_Q');  -- 'Query'
INSERT INTO UnsupportedElement VALUES ('SQU_R');  -- 'References Query'
INSERT INTO UnsupportedElement VALUES ('SQ_AP');  -- 'Actor Participant'
INSERT INTO UnsupportedElement VALUES ('SQ_AV');  -- 'Instance Attribute Value'
INSERT INTO UnsupportedElement VALUES ('SQ_CIP');  -- 'Class Instance Participant'
INSERT INTO UnsupportedElement VALUES ('SQ_COP');  -- 'Component Participant'
INSERT INTO UnsupportedElement VALUES ('SQ_CP');  -- 'Class Participant'
INSERT INTO UnsupportedElement VALUES ('SQ_CPA');  -- 'Class Participant Attribute'
INSERT INTO UnsupportedElement VALUES ('SQ_EEP');  -- 'External Entity Participant'
INSERT INTO UnsupportedElement VALUES ('SQ_FA');  -- 'Formal Attribute'
INSERT INTO UnsupportedElement VALUES ('SQ_FAV');  -- 'Formal Attribute Value'
INSERT INTO UnsupportedElement VALUES ('SQ_IA');  -- 'Informal Attribute'
INSERT INTO UnsupportedElement VALUES ('SQ_IAV');  -- 'Informal Attribute Value'
INSERT INTO UnsupportedElement VALUES ('SQ_LS');  -- 'Lifespan'
INSERT INTO UnsupportedElement VALUES ('SQ_P');  -- 'Interaction Participant'
INSERT INTO UnsupportedElement VALUES ('SQ_PP');  -- 'Package Participant'
INSERT INTO UnsupportedElement VALUES ('SQ_TM');  -- 'Timing Mark'
INSERT INTO UnsupportedElement VALUES ('SQ_TS');  -- 'Time Span'
INSERT INTO UnsupportedElement VALUES ('SR_CM');  -- 'Content Match'
INSERT INTO UnsupportedElement VALUES ('SR_CMR');  -- 'Content Match Result'
INSERT INTO UnsupportedElement VALUES ('SR_M');  -- 'Match'
INSERT INTO UnsupportedElement VALUES ('SR_NM');  -- 'Name Match'
INSERT INTO UnsupportedElement VALUES ('SR_NMR');  -- 'Name Match Result'
INSERT INTO UnsupportedElement VALUES ('SR_SR');  -- 'Search Result'
INSERT INTO UnsupportedElement VALUES ('S_EEDI');  -- 'External Entity Data Item'
INSERT INTO UnsupportedElement VALUES ('S_EEEDI');  -- 'External Entity Event Data Item'
INSERT INTO UnsupportedElement VALUES ('S_EEEDT');  -- 'External Entity Event Data'
INSERT INTO UnsupportedElement VALUES ('S_EEEVT');  -- 'External Entity Event'
INSERT INTO UnsupportedElement VALUES ('S_EEM');  -- 'External Entity in Model'
INSERT INTO UnsupportedElement VALUES ('UC_BA');  -- 'Binary Association'
INSERT INTO UnsupportedElement VALUES ('UC_E');  -- 'Extend'
INSERT INTO UnsupportedElement VALUES ('UC_G');  -- 'Generalization'
INSERT INTO UnsupportedElement VALUES ('UC_I');  -- 'Include'
INSERT INTO UnsupportedElement VALUES ('UC_UCA');  -- 'Use Case Association'
