INSERT INTO UnsupportedElement VALUES ('A_AE');  -- 'Accept Event'
INSERT INTO UnsupportedElement VALUES ('A_AEA');  -- 'Accept Event Action'
INSERT INTO UnsupportedElement VALUES ('A_AF');  -- 'Activity Final Node'
INSERT INTO UnsupportedElement VALUES ('A_AP');  -- 'Activity Partition'
INSERT INTO UnsupportedElement VALUES ('A_ATE');  -- 'Accept Time Event Action'
INSERT INTO UnsupportedElement VALUES ('A_CTL');  -- 'Control Node'
INSERT INTO UnsupportedElement VALUES ('A_DM');  -- 'Decision Merge Node'
INSERT INTO UnsupportedElement VALUES ('A_E');  -- 'Activity Edge'
INSERT INTO UnsupportedElement VALUES ('A_FF');  -- 'Flow Final Node'
INSERT INTO UnsupportedElement VALUES ('A_FJ');  -- 'Fork Join Node'
INSERT INTO UnsupportedElement VALUES ('A_GA');  -- 'Activity Diagram Action'
INSERT INTO UnsupportedElement VALUES ('A_INI');  -- 'Initial Node'
INSERT INTO UnsupportedElement VALUES ('A_N');  -- 'Activity Node'
INSERT INTO UnsupportedElement VALUES ('A_OBJ');  -- 'Object Node'
INSERT INTO UnsupportedElement VALUES ('A_SS');  -- 'Send Signal'
INSERT INTO UnsupportedElement VALUES ('COMM_LNK');  -- 'Communication Link'
INSERT INTO UnsupportedElement VALUES ('C_DG');  -- 'Delegation'
INSERT INTO UnsupportedElement VALUES ('C_RID');  -- 'Interface Reference In Delegation'
INSERT INTO UnsupportedElement VALUES ('IA_UCP');  -- 'Use Case Participant'
INSERT INTO UnsupportedElement VALUES ('MSG_A');  -- 'Message Argument'
INSERT INTO UnsupportedElement VALUES ('MSG_AM');  -- 'Asynchronous Message'
INSERT INTO UnsupportedElement VALUES ('MSG_B');  -- 'Bridge Message'
INSERT INTO UnsupportedElement VALUES ('MSG_BA');  -- 'Bridge Argument'
INSERT INTO UnsupportedElement VALUES ('MSG_E');  -- 'Event Message'
INSERT INTO UnsupportedElement VALUES ('MSG_EA');  -- 'Event Argument'
INSERT INTO UnsupportedElement VALUES ('MSG_EPA');  -- 'Executable Property Argument'
INSERT INTO UnsupportedElement VALUES ('MSG_F');  -- 'Function Message'
INSERT INTO UnsupportedElement VALUES ('MSG_FA');  -- 'Function Argument'
INSERT INTO UnsupportedElement VALUES ('MSG_IA');  -- 'Informal Argument'
INSERT INTO UnsupportedElement VALUES ('MSG_IAM');  -- 'Informal Asynchronous Message'
INSERT INTO UnsupportedElement VALUES ('MSG_IOP');  -- 'Interface Operation Message'
INSERT INTO UnsupportedElement VALUES ('MSG_ISM');  -- 'Informal Synchronous Message'
INSERT INTO UnsupportedElement VALUES ('MSG_M');  -- 'Message'
INSERT INTO UnsupportedElement VALUES ('MSG_O');  -- 'Operation Message'
INSERT INTO UnsupportedElement VALUES ('MSG_OA');  -- 'Operation Argument'
INSERT INTO UnsupportedElement VALUES ('MSG_R');  -- 'Return Message'
INSERT INTO UnsupportedElement VALUES ('MSG_SIG');  -- 'Signal Message'
INSERT INTO UnsupportedElement VALUES ('MSG_SM');  -- 'Synchronous Message'
INSERT INTO UnsupportedElement VALUES ('O_DEF');  -- 'Deferral'
INSERT INTO UnsupportedElement VALUES ('R_COMP');  -- 'Derived Association'
INSERT INTO UnsupportedElement VALUES ('R_CONE');  -- 'Class As Derived One Side'
INSERT INTO UnsupportedElement VALUES ('R_COTH');  -- 'Class As Derived Other Side'
INSERT INTO UnsupportedElement VALUES ('SEN_ALE');  -- 'Action Language Engine'
INSERT INTO UnsupportedElement VALUES ('SEN_DCE');  -- 'Declarations Engine'
INSERT INTO UnsupportedElement VALUES ('SEN_DE');  -- 'Description Engine'
INSERT INTO UnsupportedElement VALUES ('SEN_E');  -- 'Search Engine'
INSERT INTO UnsupportedElement VALUES ('SEN_RE');  -- 'References Engine'
INSERT INTO UnsupportedElement VALUES ('SM_MEAH');  -- 'Mealy Action Home'
INSERT INTO UnsupportedElement VALUES ('SM_MEALY');  -- 'Mealy State Machine'
INSERT INTO UnsupportedElement VALUES ('SM_SDI');  -- 'Supplemental Data Items'
INSERT INTO UnsupportedElement VALUES ('SM_SGEVT');  -- 'Signal Event'
INSERT INTO UnsupportedElement VALUES ('SM_SUPDT');  -- 'Event Supplemental Data'
INSERT INTO UnsupportedElement VALUES ('SP_ALS');  -- 'Action Language Searchable'
INSERT INTO UnsupportedElement VALUES ('SP_DS');  -- 'Description Searchable'
INSERT INTO UnsupportedElement VALUES ('SP_NS');  -- 'Named Searchable'
INSERT INTO UnsupportedElement VALUES ('SP_SE');  -- 'Searchable Element'
INSERT INTO UnsupportedElement VALUES ('SP_SP');  -- 'Search Participant'
INSERT INTO UnsupportedElement VALUES ('SQU_A');  -- 'Action Language Query'
INSERT INTO UnsupportedElement VALUES ('SQU_D');  -- 'Declaration Query'
INSERT INTO UnsupportedElement VALUES ('SQU_DE');  -- 'Description Query'
INSERT INTO UnsupportedElement VALUES ('SQU_Q');  -- 'Query'
INSERT INTO UnsupportedElement VALUES ('SQU_R');  -- 'References Query'
INSERT INTO UnsupportedElement VALUES ('SQ_AP');  -- 'Actor Participant'
INSERT INTO UnsupportedElement VALUES ('SQ_AV');  -- 'Instance Attribute Value'
INSERT INTO UnsupportedElement VALUES ('SQ_CIP');  -- 'Class Instance Participant'
INSERT INTO UnsupportedElement VALUES ('SQ_COP');  -- 'Component Participant'
INSERT INTO UnsupportedElement VALUES ('SQ_CP');  -- 'Class Participant'
INSERT INTO UnsupportedElement VALUES ('SQ_CPA');  -- 'Class Participant Attribute'
INSERT INTO UnsupportedElement VALUES ('SQ_EEP');  -- 'External Entity Participant'
INSERT INTO UnsupportedElement VALUES ('SQ_FA');  -- 'Formal Attribute'
INSERT INTO UnsupportedElement VALUES ('SQ_FAV');  -- 'Formal Attribute Value'
INSERT INTO UnsupportedElement VALUES ('SQ_IA');  -- 'Informal Attribute'
INSERT INTO UnsupportedElement VALUES ('SQ_IAV');  -- 'Informal Attribute Value'
INSERT INTO UnsupportedElement VALUES ('SQ_LS');  -- 'Lifespan'
INSERT INTO UnsupportedElement VALUES ('SQ_P');  -- 'Interaction Participant'
INSERT INTO UnsupportedElement VALUES ('SQ_PP');  -- 'Package Participant'
INSERT INTO UnsupportedElement VALUES ('SQ_TM');  -- 'Timing Mark'
INSERT INTO UnsupportedElement VALUES ('SQ_TS');  -- 'Time Span'
INSERT INTO UnsupportedElement VALUES ('SR_CM');  -- 'Content Match'
INSERT INTO UnsupportedElement VALUES ('SR_CMR');  -- 'Content Match Result'
INSERT INTO UnsupportedElement VALUES ('SR_M');  -- 'Match'
INSERT INTO UnsupportedElement VALUES ('SR_NM');  -- 'Name Match'
INSERT INTO UnsupportedElement VALUES ('SR_NMR');  -- 'Name Match Result'
INSERT INTO UnsupportedElement VALUES ('SR_SR');  -- 'Search Result'
INSERT INTO UnsupportedElement VALUES ('S_EEDI');  -- 'External Entity Data Item'
INSERT INTO UnsupportedElement VALUES ('S_EEEDI');  -- 'External Entity Event Data Item'
INSERT INTO UnsupportedElement VALUES ('S_EEEDT');  -- 'External Entity Event Data'
INSERT INTO UnsupportedElement VALUES ('S_EEEVT');  -- 'External Entity Event'
INSERT INTO UnsupportedElement VALUES ('S_EEM');  -- 'External Entity in Model'
INSERT INTO UnsupportedElement VALUES ('UC_BA');  -- 'Binary Association'
INSERT INTO UnsupportedElement VALUES ('UC_E');  -- 'Extend'
INSERT INTO UnsupportedElement VALUES ('UC_G');  -- 'Generalization'
INSERT INTO UnsupportedElement VALUES ('UC_I');  -- 'Include'
INSERT INTO UnsupportedElement VALUES ('UC_UCA');  -- 'Use Case Association'
INSERT INTO UnsupportedElement VALUES ('ACT_ACT');  -- 'Body'
INSERT INTO UnsupportedElement VALUES ('ACT_AI');  -- 'Assign to Member'
INSERT INTO UnsupportedElement VALUES ('ACT_BIC');  -- 'Body in Component'
INSERT INTO UnsupportedElement VALUES ('ACT_BIE');  -- 'Body in Element'
INSERT INTO UnsupportedElement VALUES ('ACT_BLK');  -- 'Block'
INSERT INTO UnsupportedElement VALUES ('ACT_BRB');  -- 'Bridge Body'
INSERT INTO UnsupportedElement VALUES ('ACT_BRG');  -- 'Bridge Invocation'
INSERT INTO UnsupportedElement VALUES ('ACT_BRK');  -- 'Break'
INSERT INTO UnsupportedElement VALUES ('ACT_CNV');  -- 'Create No Variable'
INSERT INTO UnsupportedElement VALUES ('ACT_CON');  -- 'Continue'
INSERT INTO UnsupportedElement VALUES ('ACT_CR');  -- 'Create'
INSERT INTO UnsupportedElement VALUES ('ACT_CTL');  -- 'Control'
INSERT INTO UnsupportedElement VALUES ('ACT_DAB');  -- 'Derived Attribute Body'
INSERT INTO UnsupportedElement VALUES ('ACT_DEL');  -- 'Delete'
INSERT INTO UnsupportedElement VALUES ('ACT_E');  -- 'Else Stmt'
INSERT INTO UnsupportedElement VALUES ('ACT_EL');  -- 'ElseIf Stmt'
INSERT INTO UnsupportedElement VALUES ('ACT_FIO');  -- 'Select From Instances'
INSERT INTO UnsupportedElement VALUES ('ACT_FIW');  -- 'Select From Instances Where'
INSERT INTO UnsupportedElement VALUES ('ACT_FNB');  -- 'Function Body'
INSERT INTO UnsupportedElement VALUES ('ACT_FNC');  -- 'Function Invocation'
INSERT INTO UnsupportedElement VALUES ('ACT_FOR');  -- 'For Stmt'
INSERT INTO UnsupportedElement VALUES ('ACT_IF');  -- 'If Stmt'
INSERT INTO UnsupportedElement VALUES ('ACT_IOP');  -- 'Interface Operation Invocation'
INSERT INTO UnsupportedElement VALUES ('ACT_LNK');  -- 'Chain Link'
INSERT INTO UnsupportedElement VALUES ('ACT_OPB');  -- 'Operation Body'
INSERT INTO UnsupportedElement VALUES ('ACT_POB');  -- 'Provided Operation Body'
INSERT INTO UnsupportedElement VALUES ('ACT_PSB');  -- 'Provided Signal Body'
INSERT INTO UnsupportedElement VALUES ('ACT_REL');  -- 'Relate'
INSERT INTO UnsupportedElement VALUES ('ACT_RET');  -- 'Return Stmt'
INSERT INTO UnsupportedElement VALUES ('ACT_ROB');  -- 'Required Operation Body'
INSERT INTO UnsupportedElement VALUES ('ACT_RSB');  -- 'Required Signal Body'
INSERT INTO UnsupportedElement VALUES ('ACT_RU');  -- 'Relate Using'
INSERT INTO UnsupportedElement VALUES ('ACT_SAB');  -- 'State Action Body'
INSERT INTO UnsupportedElement VALUES ('ACT_SEL');  -- 'Select'
INSERT INTO UnsupportedElement VALUES ('ACT_SGN');  -- 'Signal Invocation'
INSERT INTO UnsupportedElement VALUES ('ACT_SMT');  -- 'Statement'
INSERT INTO UnsupportedElement VALUES ('ACT_SR');  -- 'Select Related By'
INSERT INTO UnsupportedElement VALUES ('ACT_SRW');  -- 'Select Related Where'
INSERT INTO UnsupportedElement VALUES ('ACT_TAB');  -- 'Transition Action Body'
INSERT INTO UnsupportedElement VALUES ('ACT_TFM');  -- 'Operation Invocation'
INSERT INTO UnsupportedElement VALUES ('ACT_UNR');  -- 'Unrelate'
INSERT INTO UnsupportedElement VALUES ('ACT_URU');  -- 'Unrelate Using'
INSERT INTO UnsupportedElement VALUES ('ACT_WHL');  -- 'While Stmt'
INSERT INTO UnsupportedElement VALUES ('BP_BP');  -- 'Breakpoint'
INSERT INTO UnsupportedElement VALUES ('BP_CON');  -- 'Condition'
INSERT INTO UnsupportedElement VALUES ('BP_EV');  -- 'Event Breakpoint'
INSERT INTO UnsupportedElement VALUES ('BP_OAL');  -- 'OAL Breakpoint'
INSERT INTO UnsupportedElement VALUES ('BP_ST');  -- 'State Breakpoint'
INSERT INTO UnsupportedElement VALUES ('CSME_CIE');  -- 'Class In Engine'
INSERT INTO UnsupportedElement VALUES ('CSME_CIS');  -- 'Class In State'
INSERT INTO UnsupportedElement VALUES ('CSME_CLM');  -- 'Class Monitor'
INSERT INTO UnsupportedElement VALUES ('E_CEA');  -- 'Create Event to Class'
INSERT INTO UnsupportedElement VALUES ('E_CEC');  -- 'Create Event to Creator'
INSERT INTO UnsupportedElement VALUES ('E_CEE');  -- 'Create Event to External Entity'
INSERT INTO UnsupportedElement VALUES ('E_CEI');  -- 'Create Event to Instance'
INSERT INTO UnsupportedElement VALUES ('E_CES');  -- 'Create Event Statement'
INSERT INTO UnsupportedElement VALUES ('E_CSME');  -- 'Create SM Event Statement'
INSERT INTO UnsupportedElement VALUES ('E_ESS');  -- 'Event Specification Statement'
INSERT INTO UnsupportedElement VALUES ('E_GAR');  -- 'Generate to Class'
INSERT INTO UnsupportedElement VALUES ('E_GEC');  -- 'Generate to Creator'
INSERT INTO UnsupportedElement VALUES ('E_GEE');  -- 'Generate to External Entity'
INSERT INTO UnsupportedElement VALUES ('E_GEN');  -- 'Generate'
INSERT INTO UnsupportedElement VALUES ('E_GES');  -- 'Generate Event Statement'
INSERT INTO UnsupportedElement VALUES ('E_GPR');  -- 'Generate Preexisting Event'
INSERT INTO UnsupportedElement VALUES ('E_GSME');  -- 'Generate SM Event Statement'
INSERT INTO UnsupportedElement VALUES ('G_EIS');  -- 'Global Element in System'
INSERT INTO UnsupportedElement VALUES ('I_AVL');  -- 'Attribute Value'
INSERT INTO UnsupportedElement VALUES ('I_BSF');  -- 'Block in Stack Frame'
INSERT INTO UnsupportedElement VALUES ('I_CIN');  -- 'Component Instance Container'
INSERT INTO UnsupportedElement VALUES ('I_DIV');  -- 'Data Item Value'
INSERT INTO UnsupportedElement VALUES ('I_EQE');  -- 'Event Queue Entry'
INSERT INTO UnsupportedElement VALUES ('I_EVI');  -- 'Pending Event'
INSERT INTO UnsupportedElement VALUES ('I_EXE');  -- 'Component Instance'
INSERT INTO UnsupportedElement VALUES ('I_IBO');  -- 'Instance Bound Operation'
INSERT INTO UnsupportedElement VALUES ('I_ICQE');  -- 'Intercomponent Queue Entry'
INSERT INTO UnsupportedElement VALUES ('I_INS');  -- 'Instance'
INSERT INTO UnsupportedElement VALUES ('I_LIP');  -- 'Link Participation'
INSERT INTO UnsupportedElement VALUES ('I_LNK');  -- 'Link'
INSERT INTO UnsupportedElement VALUES ('I_MON');  -- 'Monitor'
INSERT INTO UnsupportedElement VALUES ('I_RCH');  -- 'Runtime Channel'
INSERT INTO UnsupportedElement VALUES ('I_SQE');  -- 'Self Queue Entry'
INSERT INTO UnsupportedElement VALUES ('I_STACK');  -- 'Stack'
INSERT INTO UnsupportedElement VALUES ('I_STF');  -- 'Stack Frame'
INSERT INTO UnsupportedElement VALUES ('I_TIM');  -- 'Timer'
INSERT INTO UnsupportedElement VALUES ('I_VSF');  -- 'Value in Stack Frame'
INSERT INTO UnsupportedElement VALUES ('L_IIR');  -- 'Instance in Reference'
INSERT INTO UnsupportedElement VALUES ('L_IWC');  -- 'Instance in Where Clause'
INSERT INTO UnsupportedElement VALUES ('L_LCL');  -- 'Local'
INSERT INTO UnsupportedElement VALUES ('L_LCR');  -- 'Local Reference'
INSERT INTO UnsupportedElement VALUES ('L_LSR');  -- 'Local Selected Reference'
INSERT INTO UnsupportedElement VALUES ('L_LVL');  -- 'Local Value'
INSERT INTO UnsupportedElement VALUES ('MI_II');  -- 'Integrity Issue'
INSERT INTO UnsupportedElement VALUES ('MI_IM');  -- 'Integrity Manager'
INSERT INTO UnsupportedElement VALUES ('O_RAVR');  -- 'Referential Attribute Visited Recorder'
INSERT INTO UnsupportedElement VALUES ('PA_DIC');  -- 'Delegation In Component'
INSERT INTO UnsupportedElement VALUES ('PA_SIC');  -- 'Satisfaction In Component'
INSERT INTO UnsupportedElement VALUES ('PE_CRS');  -- 'Component Result Set'
INSERT INTO UnsupportedElement VALUES ('PE_CVS');  -- 'Component Visibility'
INSERT INTO UnsupportedElement VALUES ('PE_SRS');  -- 'Search Result Set'
INSERT INTO UnsupportedElement VALUES ('PE_VIS');  -- 'Element Visibility'
INSERT INTO UnsupportedElement VALUES ('P_P');  -- 'Proposal'
INSERT INTO UnsupportedElement VALUES ('P_PCC');  -- 'Proposal Calculation Cue'
INSERT INTO UnsupportedElement VALUES ('P_PL');  -- 'Proposal List'
INSERT INTO UnsupportedElement VALUES ('RV_AVL');  -- 'Array Value'
INSERT INTO UnsupportedElement VALUES ('RV_CRV');  -- 'Component Reference Value'
INSERT INTO UnsupportedElement VALUES ('RV_IRV');  -- 'Instance Reference Value'
INSERT INTO UnsupportedElement VALUES ('RV_RVL');  -- 'Runtime Value'
INSERT INTO UnsupportedElement VALUES ('RV_SCV');  -- 'Simple Core Value'
INSERT INTO UnsupportedElement VALUES ('RV_SMV');  -- 'Simple Value'
INSERT INTO UnsupportedElement VALUES ('RV_SVL');  -- 'Structured Value'
INSERT INTO UnsupportedElement VALUES ('RV_VIA');  -- 'Value In Array'
INSERT INTO UnsupportedElement VALUES ('RV_VIS');  -- 'Value In Structure'
INSERT INTO UnsupportedElement VALUES ('V_AER');  -- 'Array Element Reference'
INSERT INTO UnsupportedElement VALUES ('V_ALV');  -- 'Array Length Value'
INSERT INTO UnsupportedElement VALUES ('V_AVL');  -- 'Attribute Value Reference'
INSERT INTO UnsupportedElement VALUES ('V_BIN');  -- 'Binary Operation'
INSERT INTO UnsupportedElement VALUES ('V_BRV');  -- 'Bridge Value'
INSERT INTO UnsupportedElement VALUES ('V_EDV');  -- 'Event Datum Value'
INSERT INTO UnsupportedElement VALUES ('V_EPR');  -- 'Event Parameter Reference'
INSERT INTO UnsupportedElement VALUES ('V_FNV');  -- 'Function Value'
INSERT INTO UnsupportedElement VALUES ('V_INS');  -- 'Instance Set'
INSERT INTO UnsupportedElement VALUES ('V_INT');  -- 'Instance Handle'
INSERT INTO UnsupportedElement VALUES ('V_IRF');  -- 'Instance Reference'
INSERT INTO UnsupportedElement VALUES ('V_ISR');  -- 'Instance Set Reference'
INSERT INTO UnsupportedElement VALUES ('V_LBO');  -- 'Literal Boolean'
INSERT INTO UnsupportedElement VALUES ('V_LEN');  -- 'Literal Enumerator'
INSERT INTO UnsupportedElement VALUES ('V_LIN');  -- 'Literal Integer'
INSERT INTO UnsupportedElement VALUES ('V_LOC');  -- 'Variable Location'
INSERT INTO UnsupportedElement VALUES ('V_LRL');  -- 'Literal Real'
INSERT INTO UnsupportedElement VALUES ('V_LST');  -- 'Literal String'
INSERT INTO UnsupportedElement VALUES ('V_MSV');  -- 'Message Value'
INSERT INTO UnsupportedElement VALUES ('V_MVL');  -- 'Member Value Reference'
INSERT INTO UnsupportedElement VALUES ('V_PAR');  -- 'Actual Parameter'
INSERT INTO UnsupportedElement VALUES ('V_PVL');  -- 'Parameter Value'
INSERT INTO UnsupportedElement VALUES ('V_SCV');  -- 'Symbolic Constant Value'
INSERT INTO UnsupportedElement VALUES ('V_SLR');  -- 'Selected Reference'
INSERT INTO UnsupportedElement VALUES ('V_TRN');  -- 'Transient Var'
INSERT INTO UnsupportedElement VALUES ('V_TRV');  -- 'Operation Value'
INSERT INTO UnsupportedElement VALUES ('V_TVL');  -- 'Transient Value Reference'
INSERT INTO UnsupportedElement VALUES ('V_UNY');  -- 'Unary Operation'
INSERT INTO UnsupportedElement VALUES ('V_VAL');  -- 'Value'
INSERT INTO UnsupportedElement VALUES ('V_VAR');  -- 'Variable'
