= Combined Attribute Fix

xtUML Project Implementation Note

== 1 Abstract

In <<dr-1>>, the result of combining a base attribute with a referential results
in any formalizations made on the combined reference to have the datatype
defaulted to integer.

== 2 Introduction and Background

Combined referentials are restricted to a combination of base identifier 
attribute combined with a referential attribute, that resolves back to the same 
base, or a combination of referential attributes that resolve back to the same 
base attribute. This is done to constrain relationship loops and adds a benefit
of removing clutter from the class model.

The implementation of combined referentials in the OOAofOOA is all done in the
process models (OAL).

The process of combination involves making one attribute the root of the
combination and deleting the other attributes. All combinations are done as
referential attributes, so in the base and referential case, the base attribute
must be first migrated to referential.

== 3 Requirements

Formalizations on a combined referential must retain the datatype of the
referred to attribute.

== 4 Work Required

Determine how to set the datatype without having a base attribute, and add that
to the OAL where new referential attributes are created.

=== 4.1 Observations
Cause of datatype being set to integer is ReferentialAttribute.setDataType
doesn't find a base attribute. In the OAL, ReferentialAttribute.setDataType is 
only called from Attribute.migrateBaseToReferential, but it was observed to be
called during model loading as well.

Attribute.migrateBaseToReferential is only called in two places,
Attribute.combine_refs and ModelClass.newReferentialAttribute. The error occurs
in the call from ModelClass.newReferentialAttribute.

=== 4.2 Dead code

Attribute.migrateBaseToReferential performs a dispose of the base attribute as
it's first step. ReferentialAttribute.setDataType checks for the base attribute
as it's first step, and does nothing if no base attribute is found. This makes
the call to ReferentialAttribute.setDataType from
Attribute.migrateBaseToReferential "dead code".

== 5 Implementation Comments

It seems to me that the whole handling of combined referentials would be greatly
simplified, if it was added to the Subsystem class model in the OOAofOOA.

The deletion of the base attribute is a kludge, that is probably going to cause
other issues.

== 6 Unit Test

Outline all the unit tests that need to pass and describe the method that you
will use to design and perform the tests.

. Here is another ordered list element allowing the renderer to do the work.
  This may be better for unit test steps that do not get explicitly referenced.
. second one
  .. enumerated sub first
  .. enumerated sub second
. third

== 7 User Documentation

Describe the end user documentation that was added for this change.

== 8 Code Changes

- fork/repository:  your_fork/repo_name
- branch:  your_branch_name_here

----
 Put the file list here
----

== 9 Document References

. [[dr-1]] https://support.onefact.net/issues/11556[11556 - Merging referentials causes datatype to be lost]

---

This work is licensed under the Creative Commons CC0 License

---
